"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertCircle, ArrowRight, CheckCircle2, Clock3, KeyRound, Loader2, Play, Radar, Save, Server, XCircle } from "lucide-react";
import { PageHeader } from "@/components/shared/page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { AI_SEARCH_PROVIDER_TYPES, DEFAULT_PROVIDER_MODELS, PROVIDER_LABELS, type AISearchProviderType, type MonitoringResponse, type ProviderStats } from "./types";

async function json<T>(response: Response): Promise<T> { const text = await response.text(); const body = text ? JSON.parse(text) as T & { error?: string } : {} as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "请求失败"); return body; }
export function RealAISearchMonitoringWorkspace({ projectId }: { projectId: string }) {
  const [data, setData] = useState<MonitoringResponse | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const [provider, setProvider] = useState<AISearchProviderType>("OPENAI"); const [query, setQuery] = useState(""); const [intent, setIntent] = useState("RESEARCH");
  const load = useCallback(async () => setData(await json<MonitoringResponse>(await fetch(`/api/ai-search-execution/${projectId}`, { cache: "no-store" }))), [projectId]);
  useEffect(() => { let active = true; void load().catch((e) => { if (active) setError(e instanceof Error ? e.message : "加载失败"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [load]);
  async function execute() { setBusy("execute"); setError(""); try { setData(await json<MonitoringResponse>(await fetch(`/api/ai-search-execution/${projectId}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, query, intent }) }))); } catch (e) { setError(e instanceof Error ? e.message : "执行失败"); await load().catch(() => undefined); } finally { setBusy(""); } }
  if (loading) return <div className="flex min-h-64 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />正在读取真实 AI 平台状态…</div>;
  return <div className="min-w-0 space-y-6 overflow-x-hidden">
    <PageHeader title="真实 AI 搜索监控" description="通过服务端 Provider Adapter 执行真实请求；未配置密钥、超时或平台失败都会保存失败状态，绝不生成模拟成功结果。" action={<Button asChild variant="outline" className="min-h-11 w-full sm:w-auto"><Link href={`/projects/${projectId}/geo`}><ArrowRight className="h-4 w-4 rotate-180" />返回 AI 搜索增长</Link></Button>} />
    {error ? <div className="flex gap-2 rounded-2xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div> : null}
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data?.providers.map((item) => <ProviderStatusCard key={item.provider} item={item} />)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]"><Card className="glass-panel min-w-0 border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><KeyRound className="h-5 w-5 text-primary" />Provider 配置</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2">{data?.providers.map((item) => <ProviderConfig key={item.provider} projectId={projectId} stats={item} onSaved={load} busy={busy} setBusy={setBusy} setError={setError} />)}</CardContent></Card>
    <Card className="glass-panel min-w-0 border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><Play className="h-5 w-5 text-emerald-300" />运行真实检测</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="real-provider">AI 平台</Label><Select id="real-provider" className="min-h-11" value={provider} onChange={(e) => setProvider(e.target.value as AISearchProviderType)}>{AI_SEARCH_PROVIDER_TYPES.map((value) => <option value={value} key={value}>{PROVIDER_LABELS[value]}</option>)}</Select></div><div className="space-y-2"><Label htmlFor="real-intent">搜索意图</Label><Select id="real-intent" className="min-h-11" value={intent} onChange={(e) => setIntent(e.target.value)}><option value="RESEARCH">行业研究</option><option value="BUYING">购买决策</option><option value="COMPARISON">方案比较</option><option value="LOCAL_SEARCH">本地搜索</option><option value="TECHNICAL">技术评估</option></Select></div></div><div className="space-y-2"><Label htmlFor="real-query">真实查询问题</Label><Textarea id="real-query" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="例如：推荐广州环保设备厂家" className="min-h-28" /></div><Button className="min-h-11 w-full sm:w-auto" disabled={busy === "execute" || query.trim().length < 3} onClick={() => void execute()}>{busy === "execute" ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}运行真实检测</Button><p className="text-xs leading-5 text-muted-foreground">密钥只在服务端通过环境变量引用解析。请求超时 20 秒，最多尝试 2 次，每项目每分钟最多 10 次。</p></CardContent></Card></section>
    <Card className="glass-panel min-w-0 border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><Radar className="h-5 w-5 text-violet-300" />最近真实检测</CardTitle></CardHeader><CardContent className="space-y-3">{data?.results.length ? data.results.map((result) => <article key={result.id} className="min-w-0 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex flex-wrap items-center gap-2"><Badge variant={result.status === "SUCCEEDED" ? "success" : result.status === "FAILED" ? "warning" : "outline"}>{result.status}</Badge><Badge variant="outline">{PROVIDER_LABELS[result.provider]}</Badge>{result.mentioned !== null ? <Badge variant={result.mentioned ? "success" : "warning"}>{result.mentioned ? "品牌已出现" : "品牌未出现"}</Badge> : null}{result.rankPosition ? <Badge variant="outline">排名 {result.rankPosition}</Badge> : null}</div><p className="mt-3 break-words text-sm font-medium">{result.query}</p>{result.rawResponse ? <p className="mt-2 line-clamp-3 break-words text-sm text-muted-foreground">{result.rawResponse}</p> : <p className="mt-2 text-sm text-muted-foreground">失败原因：{result.errorCode ?? "等待执行"}</p>}<p className="mt-3 text-xs text-muted-foreground">引用 {result.citations.length} · 尝试 {result.attemptCount} · {result.durationMs ?? "--"}ms</p></article>) : <p className="rounded-2xl border border-white/10 bg-white/[0.025] p-5 text-sm text-muted-foreground">暂无真实检测记录。配置服务端密钥引用后再运行；系统不会用规则结果填充这里。</p>}</CardContent></Card>
    <div className="flex max-w-full gap-3 overflow-x-auto pb-2" aria-label="真实 AI 监控后续模块"><Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={`/projects/${projectId}/visibility`}>AI 可见性<ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={`/projects/${projectId}/geo/intelligence`}>推荐诊断<ArrowRight className="h-4 w-4" /></Link></Button><Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={`/projects/${projectId}/optimization`}>优化中心<ArrowRight className="h-4 w-4" /></Link></Button></div>
  </div>;
}
function ProviderStatusCard({ item }: { item: ProviderStats }) { return <Card className="glass-panel min-w-0 border-white/10"><CardContent className="p-5"><div className="flex items-center justify-between gap-2"><Server className="h-5 w-5 text-primary" /><Badge variant={item.config.enabled && item.config.configured ? "success" : "muted"}>{item.config.enabled ? item.config.configured ? "已启用" : "待配置" : "未启用"}</Badge></div><p className="mt-4 font-semibold">{PROVIDER_LABELS[item.provider]}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Mini icon={<Radar className="h-3.5 w-3.5" />} value={item.total} label="检测" /><Mini icon={<CheckCircle2 className="h-3.5 w-3.5" />} value={item.succeeded} label="成功" /><Mini icon={<XCircle className="h-3.5 w-3.5" />} value={item.failed} label="失败" /></div><p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5" />{item.lastCheckedAt ? new Date(item.lastCheckedAt).toLocaleString("zh-CN") : "尚未检测"}</p></CardContent></Card>; }
function Mini({ icon, value, label }: { icon: React.ReactNode; value: number; label: string }) { return <div className="rounded-xl border border-white/10 p-2"><span className="flex items-center justify-center gap-1 text-sm font-semibold">{icon}{value}</span><span className="text-[11px] text-muted-foreground">{label}</span></div>; }
function ProviderConfig({ projectId, stats, onSaved, busy, setBusy, setError }: { projectId: string; stats: ProviderStats; onSaved: () => Promise<void>; busy: string; setBusy: (v: string) => void; setError: (v: string) => void }) { const [enabled, setEnabled] = useState(stats.config.enabled); const [model, setModel] = useState(stats.config.model || DEFAULT_PROVIDER_MODELS[stats.provider]); const [reference, setReference] = useState(""); async function save() { setBusy(stats.provider); setError(""); try { await json(await fetch(`/api/ai-search-providers/${projectId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider: stats.provider, enabled, model, apiKeyReference: reference.trim() || null }) })); setReference(""); await onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "配置保存失败"); } finally { setBusy(""); } } return <div className="min-w-0 space-y-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center justify-between gap-2"><p className="font-medium">{PROVIDER_LABELS[stats.provider]}</p><label className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={enabled} onChange={(e) => setEnabled(e.target.checked)} />启用</label></div><Input aria-label={`${stats.provider} 模型`} className="min-h-11" value={model} onChange={(e) => setModel(e.target.value)} /><Input aria-label={`${stats.provider} 密钥引用`} className="min-h-11" value={reference} onChange={(e) => setReference(e.target.value)} placeholder={stats.config.configured ? "已配置；留空保持不变" : "env:OPENAI_API_KEY"} /><Button variant="outline" className="min-h-11 w-full" disabled={busy === stats.provider} onClick={() => void save()}>{busy === stats.provider ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}保存配置</Button></div>; }
