import { realAISearchDatabase, type Row } from "@/features/real-ai-search/database";
import type { GrowthActionView } from "@/features/growth-actions/types";
import type { AgentExpectedImpact, AgentPlanStep, AgentVerificationCheck, GrowthAgentCandidate, GrowthAgentTaskStatus, GrowthAgentTaskView } from "./types";

const iso = (value: unknown) => value ? new Date(String(value)).toISOString() : null;
function json<T>(value: unknown, fallback: T): T { if (value && typeof value === "object") return value as T; if (typeof value === "string") { try { return JSON.parse(value) as T; } catch { return fallback; } } return fallback; }
function actionView(row: Row): GrowthAgentTaskView["action"] { return { id: String(row.actionId), title: String(row.actionTitle), sourceType: String(row.actionSourceType), optimizationTaskId: row.actionOptimizationTaskId ? String(row.actionOptimizationTaskId) : null, status: String(row.actionStatus) as GrowthActionView["status"] }; }
function view(row: Row): GrowthAgentTaskView { return { id: String(row.id), projectId: String(row.projectId), actionId: String(row.actionId), title: String(row.title), description: String(row.description), category: String(row.category) as GrowthAgentTaskView["category"], status: String(row.status) as GrowthAgentTaskStatus, priority: String(row.priority) as GrowthAgentTaskView["priority"], confidence: Number(row.confidence), expectedImpact: json<AgentExpectedImpact>(row.expectedImpact, { status: "unavailable", metrics: [] }), executionPlan: json<AgentPlanStep[]>(row.executionPlan, []), verificationPlan: json<AgentVerificationCheck[]>(row.verificationPlan, []), generatedAt: iso(row.generatedAt) ?? new Date(0).toISOString(), completedAt: iso(row.completedAt), createdAt: iso(row.createdAt) ?? new Date(0).toISOString(), action: actionView(row) }; }
const select = 'SELECT task.*, action."title" AS "actionTitle", action."sourceType" AS "actionSourceType", action."optimizationTaskId" AS "actionOptimizationTaskId", action."status" AS "actionStatus" FROM "GrowthAgentTask" task INNER JOIN "GrowthAction" action ON action."id" = task."actionId" INNER JOIN "Project" p ON p."id" = task."projectId"';

export const growthAgentRepository = {
  async projectOwned(userId: string, projectId: string) { return Boolean((await realAISearchDatabase().query('SELECT 1 FROM "Project" WHERE "id" = $1 AND "userId" = $2', [projectId, userId]))[0]); },
  async actions(userId: string, projectId: string, actionId?: string) { const rows = await realAISearchDatabase().query(`SELECT action.* FROM "GrowthAction" action INNER JOIN "Project" p ON p."id" = action."projectId" WHERE action."projectId" = $1 AND p."userId" = $2 ${actionId ? 'AND action."id" = $3' : ''} ORDER BY action."createdAt" DESC`, actionId ? [projectId, userId, actionId] : [projectId, userId]); return rows as unknown as GrowthActionView[]; },
  async reportOwned(userId: string, projectId: string, reportId: string) { return Boolean((await realAISearchDatabase().query('SELECT 1 FROM "GrowthReport" report INNER JOIN "Project" p ON p."id" = report."projectId" WHERE report."id" = $1 AND report."projectId" = $2 AND p."userId" = $3 AND report."status" = \'COMPLETED\'::"GrowthReportStatus"', [reportId, projectId, userId]))[0]); },
  async hasReport(projectId: string) { return Boolean((await realAISearchDatabase().query('SELECT 1 FROM "GrowthReport" WHERE "projectId" = $1 AND "status" = \'COMPLETED\'::"GrowthReportStatus" LIMIT 1', [projectId]))[0]); },
  async list(userId: string, projectId: string) { return (await realAISearchDatabase().query(`${select} WHERE task."projectId" = $1 AND p."userId" = $2 ORDER BY CASE task."status" WHEN 'IN_PROGRESS' THEN 1 WHEN 'TODO' THEN 2 WHEN 'COMPLETED' THEN 3 ELSE 4 END, task."createdAt" DESC`, [projectId, userId])).map(view); },
  async insert(userId: string, projectId: string, candidates: GrowthAgentCandidate[]) { let created = 0; for (const item of candidates) { const result = await realAISearchDatabase().query('INSERT INTO "GrowthAgentTask" ("id", "projectId", "actionId", "title", "description", "category", "status", "priority", "confidence", "expectedImpact", "executionPlan", "verificationPlan", "generatedAt", "createdAt") SELECT $1, p."id", action."id", $5, $6, $7::"GrowthActionCategory", \'TODO\'::"GrowthAgentTaskStatus", $8::"GrowthActionPriority", $9, $10::jsonb, $11::jsonb, $12::jsonb, $13, $13 FROM "Project" p INNER JOIN "GrowthAction" action ON action."id" = $3 AND action."projectId" = p."id" WHERE p."id" = $2 AND p."userId" = $4 ON CONFLICT ("projectId", "actionId") DO NOTHING RETURNING "GrowthAgentTask".*', [crypto.randomUUID(), projectId, item.actionId, userId, item.title, item.description, item.category, item.priority, item.confidence, JSON.stringify(item.expectedImpact), JSON.stringify(item.executionPlan), JSON.stringify(item.verificationPlan), new Date()]); if (result[0]) created += 1; } return created; },
  async updateStatus(userId: string, projectId: string, taskId: string, status: GrowthAgentTaskStatus) { const now = new Date(); const row = (await realAISearchDatabase().query('UPDATE "GrowthAgentTask" task SET "status" = $4::"GrowthAgentTaskStatus", "completedAt" = CASE WHEN $4 IN (\'COMPLETED\', \'VERIFIED\') THEN COALESCE(task."completedAt", $5) ELSE task."completedAt" END FROM "Project" p WHERE task."id" = $1 AND task."projectId" = $2 AND task."projectId" = p."id" AND p."userId" = $3 RETURNING task.*', [taskId, projectId, userId, status, now]))[0]; if (!row) return null; const joined = (await realAISearchDatabase().query(`${select} WHERE task."id" = $1 AND task."projectId" = $2 AND p."userId" = $3`, [taskId, projectId, userId]))[0]; return joined ? view(joined) : null; },
  async timeline(userId: string, task: GrowthAgentTaskView) { await realAISearchDatabase().query('INSERT INTO "GrowthSnapshot" ("id", "projectId", "eventType", "triggerType", "sourceId", "metadata", "createdAt") SELECT $1, p."id", \'OPTIMIZATION\'::"GrowthEventType", \'AUTO\'::"GrowthTriggerType", $3, $4::jsonb, $5 FROM "Project" p WHERE p."id" = $2 AND p."userId" = $6 ON CONFLICT ("projectId", "eventType", "sourceId") DO NOTHING', [crypto.randomUUID(), task.projectId, `growth-agent:${task.id}:completed`, JSON.stringify({ growthAgentTaskId: task.id, growthActionId: task.actionId, optimizationTaskId: task.action.optimizationTaskId, title: task.title, category: task.category, completedAt: task.completedAt }), new Date(task.completedAt ?? Date.now()), userId]); },
};
