import { buildGrowthAgentCandidates } from "./growth-agent-generator";
import { growthAgentRepository } from "./repository";
import { AGENT_STATUSES, type GrowthAgentTaskStatus } from "./types";

export class GrowthAgentError extends Error { constructor(public code: string, public status: number) { super(code); } }
async function owned(userId: string, projectId: string) { if (!await growthAgentRepository.projectOwned(userId, projectId)) throw new GrowthAgentError("PROJECT_FORBIDDEN", 403); }
function overview(projectId: string, tasks: Awaited<ReturnType<typeof growthAgentRepository.list>>) { const completed = tasks.filter((task) => task.status === "COMPLETED" || task.status === "VERIFIED").length; const verified = tasks.filter((task) => task.status === "VERIFIED").length; return { projectId, tasks, summary: { total: tasks.length, completed, verified, completionRate: tasks.length ? Math.round(completed / tasks.length * 100) : 0, suggestionCount: tasks.length, expectedMetricCount: new Set(tasks.flatMap((task) => task.expectedImpact.metrics.map((metric) => metric.metric))).size, expectedGrowthValue: "unavailable" as const } }; }
export async function listGrowthAgentTasks(userId: string, projectId: string) { await owned(userId, projectId); return overview(projectId, await growthAgentRepository.list(userId, projectId)); }
export async function generateGrowthAgentTasks(userId: string, projectId: string, input: { actionId?: string; reportId?: string }) { await owned(userId, projectId); if (input.reportId && !await growthAgentRepository.reportOwned(userId, projectId, input.reportId)) throw new GrowthAgentError("REPORT_FORBIDDEN", 403); const actions = await growthAgentRepository.actions(userId, projectId, input.actionId); if (input.actionId && !actions.length) throw new GrowthAgentError("ACTION_NOT_FOUND", 404); const candidates = buildGrowthAgentCandidates(actions, Boolean(input.reportId) || await growthAgentRepository.hasReport(projectId)); if (!candidates.length) return { status: "unavailable" as const, createdCount: 0, ...overview(projectId, await growthAgentRepository.list(userId, projectId)) }; const createdCount = await growthAgentRepository.insert(userId, projectId, candidates); return { status: "available" as const, createdCount, existingCount: candidates.length - createdCount, ...overview(projectId, await growthAgentRepository.list(userId, projectId)) }; }
export async function updateGrowthAgentTask(userId: string, projectId: string, taskId: string, status: string) { await owned(userId, projectId); if (!AGENT_STATUSES.includes(status as GrowthAgentTaskStatus)) throw new GrowthAgentError("INVALID_AGENT_STATUS", 400); const current = (await growthAgentRepository.list(userId, projectId)).find((task) => task.id === taskId); if (!current) throw new GrowthAgentError("AGENT_TASK_NOT_FOUND", 404); const transitions: Record<GrowthAgentTaskStatus, GrowthAgentTaskStatus[]> = { TODO: ["TODO", "IN_PROGRESS"], IN_PROGRESS: ["IN_PROGRESS", "COMPLETED"], COMPLETED: ["COMPLETED", "VERIFIED"], VERIFIED: ["VERIFIED"] }; if (!transitions[current.status].includes(status as GrowthAgentTaskStatus)) throw new GrowthAgentError("INVALID_AGENT_TRANSITION", 409); const task = await growthAgentRepository.updateStatus(userId, projectId, taskId, status as GrowthAgentTaskStatus); if (!task) throw new GrowthAgentError("AGENT_TASK_NOT_FOUND", 404); if (status === "COMPLETED") await growthAgentRepository.timeline(userId, task); return task; }
