import type { ChangeDetectionResult, ComparisonRound, MonitoringChange } from "./types";

export function detectMonitoringChanges(current: ComparisonRound, previous: ComparisonRound | null): ChangeDetectionResult {
  if (!previous) return { status: "unavailable", previousResultId: null, currentResultId: current.id, changes: [], unavailableReason: "没有上一轮同平台成功检测结果。" };
  if (previous.provider !== current.provider) return { status: "unavailable", previousResultId: previous.id, currentResultId: current.id, changes: [], unavailableReason: "两轮结果不属于同一 AI 平台。" };
  const changes: MonitoringChange[] = [];
  if (previous.mentioned && !current.mentioned) changes.push({ type: "REAL_AI_VISIBILITY_DROP", direction: "DROP", severity: "HIGH", title: `${current.provider} 品牌推荐丢失`, description: "上一轮真实回答提及企业，本轮真实回答未提及。", previousValue: true, currentValue: false, delta: null });
  if (!previous.mentioned && current.mentioned) changes.push({ type: "REAL_AI_VISIBILITY_GAIN", direction: "IMPROVEMENT", severity: "LOW", title: `${current.provider} 品牌推荐恢复`, description: "上一轮真实回答未提及企业，本轮真实回答已提及。", previousValue: false, currentValue: true, delta: null });
  if (current.citationCount < previous.citationCount) { const drop = previous.citationCount - current.citationCount; const ratio = previous.citationCount > 0 ? drop / previous.citationCount : 0; changes.push({ type: "CITATION_DROP", direction: "DROP", severity: ratio >= 0.5 ? "HIGH" : "MEDIUM", title: `${current.provider} 引用数量下降`, description: `真实引用由 ${previous.citationCount} 降至 ${current.citationCount}。`, previousValue: previous.citationCount, currentValue: current.citationCount, delta: -drop }); }
  if (current.citationCount > previous.citationCount) changes.push({ type: "CITATION_INCREASE", direction: "IMPROVEMENT", severity: "LOW", title: `${current.provider} 引用数量提升`, description: `真实引用由 ${previous.citationCount} 增至 ${current.citationCount}。`, previousValue: previous.citationCount, currentValue: current.citationCount, delta: current.citationCount - previous.citationCount });
  if (previous.rankPosition !== null && current.rankPosition !== null && current.rankPosition > previous.rankPosition) { const drop = current.rankPosition - previous.rankPosition; changes.push({ type: "RANKING_DROP", direction: "DROP", severity: drop >= 3 ? "HIGH" : "MEDIUM", title: `${current.provider} 推荐排名下降`, description: `真实推荐排名由第 ${previous.rankPosition} 位降至第 ${current.rankPosition} 位。`, previousValue: previous.rankPosition, currentValue: current.rankPosition, delta: -drop }); }
  if (previous.rankPosition !== null && current.rankPosition !== null && current.rankPosition < previous.rankPosition) changes.push({ type: "RANKING_IMPROVED", direction: "IMPROVEMENT", severity: "LOW", title: `${current.provider} 推荐排名提升`, description: `真实推荐排名由第 ${previous.rankPosition} 位升至第 ${current.rankPosition} 位。`, previousValue: previous.rankPosition, currentValue: current.rankPosition, delta: previous.rankPosition - current.rankPosition });
  return { status: "available", previousResultId: previous.id, currentResultId: current.id, changes, unavailableReason: null };
}
