"use client";
/* eslint-disable react/jsx-key -- metric icons live in a keyed parent tuple */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertCircle, ArrowRight, Bell, CalendarClock, CheckCircle2, Clock3, ExternalLink, History, Loader2, Radar, Save, ShieldAlert, Sparkles, TrendingDown, TrendingUp, XCircle } from "lucide-react";
import { PageHeader } from "@/components/shared/page";
import { OperationFeedback, type OperationStatus } from "@/components/shared/operation-feedback";
import { MetricHelp } from "@/components/shared/metric-help";
import { metricHelpPreset, type MetricHelpKey } from "@/components/shared/metric-help-presets";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { PROVIDER_LABELS } from "@/features/real-ai-search/types";
import type { MonitoringCenterResponse, MonitoringFrequency, MonitoringScheduleView, NotificationView, ProviderMonitoringSummary } from "./types";
import { useI18n } from "@/i18n/provider";

async function readJson<T>(response: Response): Promise<T> { const text = await response.text(); const body = text ? JSON.parse(text) as T & { error?: string } : {} as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "请求失败"); return body; }
const date = (value: string | null, locale: "zh" | "en") => value ? new Date(value).toLocaleString(locale === "zh" ? "zh-CN" : "en-US") : "unavailable";
export function MonitoringCenterWorkspace({ projectId }: { projectId: string }) {
  const [data, setData] = useState<MonitoringCenterResponse | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [feedback, setFeedback] = useState<{ status: OperationStatus; message: string } | null>(null);
  const { locale } = useI18n();
  const load = useCallback(async () => setData(await readJson<MonitoringCenterResponse>(await fetch(`/api/ai-search-monitoring/${projectId}`, { cache: "no-store" }))), [projectId]);
  useEffect(() => { let active = true; void load().catch((e) => { if (active) setError(e instanceof Error ? e.message : "监控中心加载失败"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [load]);
  async function saveSchedule(schedule: MonitoringScheduleView) { if (saving) return; setSaving(true); setError(""); setFeedback({ status: "VALIDATING", message: locale === "zh" ? "正在校验并保存监控计划。" : "Validating and saving the monitoring schedule." }); try { const result = await readJson<{ schedule: MonitoringScheduleView }>(await fetch(`/api/ai-search-monitoring/${projectId}/schedule`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: schedule.enabled, frequency: schedule.frequency, dailyTime: schedule.dailyTime, timezone: schedule.timezone }) })); setData((current) => current ? { ...current, schedule: result.schedule } : current); setFeedback({ status: "COMPLETED", message: locale === "zh" ? "监控计划已保存；当前版本不会自动发起付费 Provider 请求。" : "The schedule was saved. This version does not automatically send paid provider requests." }); } catch (e) { const message = e instanceof Error ? e.message : (locale === "zh" ? "计划保存失败" : "Schedule save failed"); setError(message); setFeedback({ status: "FAILED", message }); } finally { setSaving(false); } }
  if (loading) return <div className="flex min-h-72 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin motion-reduce:animate-none" />{locale === "zh" ? "正在读取真实 AI 搜索运营状态…" : "Loading persisted AI search operations data…"}</div>;
  if (!data) return <div className="rounded-2xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-destructive">{locale === "zh" ? "AI 搜索监控中心加载失败" : "AI Search Monitoring Center failed to load"}：{error || "unavailable"}</div>;
  return <div data-testid="monitoring-center" className="min-w-0 space-y-6 overflow-x-hidden">
    <PageHeader title={locale === "zh" ? "AI 搜索监控中心（AI Search Monitoring Center）" : "AI Search Monitoring Center"} description={locale === "zh" ? `持续观察 ${data.project.name} 在四大 AI 平台中的品牌出现、推荐排名、引用和异常变化。` : `Continuously track brand mentions, recommendation rank, citations, and changes for ${data.project.name}.`} action={<Button asChild variant="outline" className="min-h-11 w-full sm:w-auto"><Link href={`/projects/${projectId}/geo/monitoring`}>{locale === "zh" ? "运行真实检测" : "Run a real check"}<ArrowRight className="h-4 w-4" /></Link></Button>} />
    {error ? <div className="flex gap-2 rounded-2xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div> : null}
    {feedback ? <OperationFeedback status={feedback.status} message={feedback.message} /> : null}
    <OperationalPulse data={data} locale={locale} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.providers.map((provider) => <ProviderCard key={provider.provider} provider={provider} locale={locale} />)}</section>
    <section className="grid min-w-0 gap-6 xl:grid-cols-[0.85fr_1.15fr]"><ScheduleCard schedule={data.schedule} saving={saving} onSave={saveSchedule} locale={locale} /><ChangePanel changes={data.recentChanges} projectId={projectId} locale={locale} /></section>
    <section className="grid min-w-0 gap-6 xl:grid-cols-2"><HistoryPanel data={data} projectId={projectId} locale={locale} /><NotificationPanel data={data} projectId={projectId} locale={locale} /></section>
    <nav aria-label={locale === "zh" ? "监控中心后续模块" : "Monitoring center next modules"} className="flex max-w-full gap-3 overflow-x-auto pb-2"><NextLink href={`/projects/${projectId}/geo/monitoring-center/history`} label={locale === "zh" ? "完整历史" : "Full history"} /><NextLink href={`/projects/${projectId}/notifications`} label={locale === "zh" ? "通知中心" : "Notifications"} /><NextLink href={`/projects/${projectId}/geo/monitoring`} label={locale === "zh" ? "真实 AI 检测" : "Real AI checks"} /><NextLink href={`/projects/${projectId}/optimization`} label={locale === "zh" ? "优化中心" : "Optimization Center"} /></nav>
  </div>;
}
function OperationalPulse({ data, locale }: { data: MonitoringCenterResponse; locale: "zh" | "en" }) { const items = [[locale === "zh" ? "最近一次检测" : "Latest check", data.summary.lastCheckAt ? date(data.summary.lastCheckAt, locale) : "unavailable", <Clock3 className="h-5 w-5" />], [locale === "zh" ? "最近下降" : "Recent drops", `${data.summary.recentDrops}`, <TrendingDown className="h-5 w-5" />], [locale === "zh" ? "最近提升" : "Recent improvements", `${data.summary.recentImprovements}`, <TrendingUp className="h-5 w-5" />], [locale === "zh" ? "待处理变化" : "Pending changes", `${data.summary.pendingChanges}`, <Bell className="h-5 w-5" />]] as const; return <Card className="glass-panel overflow-hidden border-cyan-300/20"><CardContent className="grid gap-4 p-5 lg:grid-cols-[0.7fr_0.3fr]"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label, value, icon]) => <div key={label} className="min-w-0 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><span className="text-cyan-300">{icon}</span><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-lg font-semibold">{value}</p></div>)}</div><div className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.04] p-4"><p className="flex items-center gap-2 text-sm font-medium text-amber-200"><ShieldAlert className="h-4 w-4" />{locale === "zh" ? "首要提醒" : "Top Alert"}</p><p className="mt-3 text-sm font-semibold">{data.summary.topAlert?.title ?? "unavailable"}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{data.summary.topAlert?.content ?? (locale === "zh" ? "尚无真实变化或 Provider 失败事件。" : "No real change or provider failure event is available.")}</p></div></CardContent></Card>; }
function ProviderCard({ provider, locale }: { provider: ProviderMonitoringSummary; locale: "zh" | "en" }) { return <Card className="glass-panel min-w-0 overflow-hidden border-white/10"><div className={`h-1 ${provider.status === "available" ? "bg-cyan-300" : "bg-white/10"}`} /><CardContent className="p-5"><div className="flex items-center justify-between gap-2"><Radar className="h-5 w-5 text-violet-300" /><Badge variant={provider.status === "available" ? "success" : "muted"}>{provider.status}</Badge></div><h2 className="mt-4 font-semibold">{PROVIDER_LABELS[provider.provider]}</h2><div className="mt-4 grid grid-cols-2 gap-2"><Metric label={locale === "zh" ? "最近检测" : "Latest check"} value={date(provider.latestCheckAt, locale)} /><Metric label={locale === "zh" ? "最近成功" : "Latest success"} value={date(provider.latestSuccessAt, locale)} /><Metric label={locale === "zh" ? "最近失败" : "Latest failure"} value={date(provider.latestFailureAt, locale)} /><Metric label={locale === "zh" ? "最近排名" : "Latest rank"} value={provider.latestRank === null ? "unavailable" : locale === "zh" ? `第 ${provider.latestRank} 位` : `#${provider.latestRank}`} helpKey="RECOMMENDATION_RANK" locale={locale} /><Metric label={locale === "zh" ? "最近引用" : "Latest citations"} value={provider.latestCitationCount === null ? "unavailable" : `${provider.latestCitationCount}`} helpKey="CITATION_STRENGTH" locale={locale} /><Metric label={locale === "zh" ? "品牌提及" : "Brand mention"} value={provider.latestMentioned === null ? "unavailable" : provider.latestMentioned ? (locale === "zh" ? "已提及" : "Mentioned") : (locale === "zh" ? "未提及" : "Not mentioned")} /></div><div className="mt-4 flex min-h-8 items-end gap-1" aria-label={`${provider.provider} ${locale === "zh" ? "趋势" : "trend"}`}>{provider.trend.length ? provider.trend.map((point) => <span key={point.resultId} title={`${date(point.completedAt, locale)} · ${locale === "zh" ? "排名" : "Rank"} ${point.rankPosition ?? "unavailable"} · ${locale === "zh" ? "引用" : "Citations"} ${point.citationCount}`} className={`min-h-2 flex-1 rounded-sm ${point.mentioned ? "bg-emerald-300/70" : "bg-amber-300/60"}`} style={{ height: `${Math.max(8, Math.min(32, point.citationCount * 4 + 8))}px` }} />) : <span className="text-xs text-muted-foreground">{locale === "zh" ? "趋势暂不可用" : "Trend unavailable"}</span>}</div></CardContent></Card>; }
function ScheduleCard({ schedule, saving, onSave, locale }: { schedule: MonitoringScheduleView; saving: boolean; onSave: (schedule: MonitoringScheduleView) => Promise<void>; locale: "zh" | "en" }) { const [draft, setDraft] = useState(schedule); useEffect(() => setDraft(schedule), [schedule]); return <Card className="glass-panel min-w-0 border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-cyan-300" />{locale === "zh" ? "监控计划（Monitoring Schedule）" : "Monitoring Schedule"}</CardTitle><p className="text-sm text-muted-foreground">{locale === "zh" ? "仅保存运营计划，本阶段不会自动执行 Provider 请求。" : "This stores the operations plan only; it does not automatically run provider requests."}</p></CardHeader><CardContent className="space-y-4"><label className="flex min-h-11 items-center gap-3 rounded-xl border border-white/10 px-3 text-sm"><input type="checkbox" checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} />{locale === "zh" ? "启用监控计划" : "Enable monitoring schedule"}</label><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="schedule-frequency">{locale === "zh" ? "频率" : "Frequency"}</Label><Select id="schedule-frequency" className="min-h-11" value={draft.frequency} onChange={(event) => setDraft({ ...draft, frequency: event.target.value as MonitoringFrequency })}><option value="DAILY">{locale === "zh" ? "每天" : "Daily"}</option><option value="WEEKLY">{locale === "zh" ? "每周" : "Weekly"}</option><option value="MONTHLY">{locale === "zh" ? "每月" : "Monthly"}</option></Select></div><div className="space-y-2"><Label htmlFor="schedule-time">{locale === "zh" ? "检测时间" : "Check time"}</Label><Input id="schedule-time" type="time" className="min-h-11" value={draft.dailyTime} onChange={(event) => setDraft({ ...draft, dailyTime: event.target.value })} /></div></div><div className="space-y-2"><Label htmlFor="schedule-timezone">{locale === "zh" ? "时区" : "Timezone"}</Label><Input id="schedule-timezone" className="min-h-11" value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })} /></div><div className="rounded-xl border border-white/10 bg-white/[0.025] p-3 text-xs text-muted-foreground"><p>{locale === "zh" ? "下次计划" : "Next scheduled run"}：{date(schedule.nextRunAt, locale)}</p><p className="mt-1">{locale === "zh" ? "上次运行" : "Last run"}：{date(schedule.lastRunAt, locale)}</p></div><Button className="min-h-11 w-full sm:w-auto" disabled={saving} onClick={() => void onSave(draft)}>{saving ? <Loader2 className="h-4 w-4 animate-spin motion-reduce:animate-none" /> : <Save className="h-4 w-4" />}{locale === "zh" ? "保存监控计划" : "Save monitoring schedule"}</Button></CardContent></Card>; }
function ChangePanel({ changes, projectId, locale }: { changes: NotificationView[]; projectId: string; locale: "zh" | "en" }) { return <Card className="glass-panel min-w-0 border-white/10"><CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-violet-300" />{locale === "zh" ? "最近变化" : "Recent changes"}</CardTitle><p className="mt-2 text-sm text-muted-foreground">{locale === "zh" ? "只展示真实前后轮比较产生的事件。" : "Only events produced by real consecutive-run comparisons are shown."}</p></div><Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={`/projects/${projectId}/growth`}>{locale === "zh" ? "增长时间线" : "Growth Timeline"}</Link></Button></CardHeader><CardContent className="space-y-3">{changes.length ? changes.map((item) => <AlertRow key={item.id} item={item} locale={locale} />) : <Empty text={locale === "zh" ? "没有可比较的上一轮真实结果，变化暂不可用。" : "No previous real run is available for comparison."} />}</CardContent></Card>; }
function HistoryPanel({ data, projectId, locale }: { data: MonitoringCenterResponse; projectId: string; locale: "zh" | "en" }) { return <Card className="glass-panel min-w-0 border-white/10"><CardHeader className="flex-row items-start justify-between gap-3"><CardTitle className="flex items-center gap-2"><History className="h-5 w-5 text-cyan-300" />{locale === "zh" ? "监控历史（Monitoring History）" : "Monitoring History"}</CardTitle><Button asChild variant="outline" className="min-h-11"><Link href={`/projects/${projectId}/geo/monitoring-center/history`}>{locale === "zh" ? "筛选历史" : "Filter history"}</Link></Button></CardHeader><CardContent className="space-y-3">{data.recentHistory.length ? data.recentHistory.slice(0, 5).map((item) => <div key={item.id} className="flex min-h-14 min-w-0 items-center gap-3 rounded-xl border border-white/10 p-3">{item.status === "SUCCEEDED" ? <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-300" /> : <XCircle className="h-4 w-4 shrink-0 text-rose-300" />}<span className="min-w-0 flex-1"><span className="block text-sm font-medium">{PROVIDER_LABELS[item.provider]} · {item.status}</span><span className="block truncate text-xs text-muted-foreground">{date(item.startedAt, locale)} · {item.durationMs ?? "unavailable"}ms</span></span></div>) : <Empty text={locale === "zh" ? "尚无真实检测历史。" : "No real check history is available."} />}</CardContent></Card>; }
function NotificationPanel({ data, projectId, locale }: { data: MonitoringCenterResponse; projectId: string; locale: "zh" | "en" }) { return <Card className="glass-panel min-w-0 border-white/10"><CardHeader className="flex-row items-start justify-between gap-3"><CardTitle className="flex items-center gap-2"><Bell className="h-5 w-5 text-amber-300" />{locale === "zh" ? "站内通知" : "In-app notifications"}</CardTitle><Button asChild variant="outline" className="min-h-11"><Link href={`/projects/${projectId}/notifications`}>{locale === "zh" ? "通知中心" : "Notification Center"}</Link></Button></CardHeader><CardContent className="space-y-3">{data.notifications.length ? data.notifications.slice(0, 5).map((item) => <AlertRow key={item.id} item={item} locale={locale} />) : <Empty text={locale === "zh" ? "暂无真实监控通知。" : "No real monitoring notifications are available."} />}</CardContent></Card>; }
function Metric({ label, value, helpKey, locale }: { label: string; value: string; helpKey?: MetricHelpKey; locale?: "zh" | "en" }) { const help = helpKey && locale ? metricHelpPreset(helpKey, locale) : null; return <div className="min-w-0 rounded-xl border border-white/10 p-2"><div className="flex min-w-0 items-center justify-between gap-1"><p className="text-[10px] text-muted-foreground">{label}</p>{help ? <MetricHelp label={help.label} content={help.content} /> : null}</div><p className="mt-1 break-words text-xs font-medium">{value}</p></div>; }
function AlertRow({ item, locale }: { item: NotificationView; locale: "zh" | "en" }) { return <div className="min-w-0 rounded-xl border border-white/10 bg-white/[0.025] p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant={item.level === "HIGH" ? "warning" : "outline"}>{item.level}</Badge><Badge variant={item.isRead ? "muted" : "success"}>{item.isRead ? (locale === "zh" ? "已读" : "Read") : (locale === "zh" ? "未读" : "Unread")}</Badge></div><p className="mt-2 break-words text-sm font-semibold">{item.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.content}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-white/15 p-4 text-sm text-muted-foreground">{text}</div>; }
function NextLink({ href, label }: { href: string; label: string }) { return <Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={href}>{label}<ExternalLink className="h-4 w-4" /></Link></Button>; }
