"use client";
/* eslint-disable react/jsx-key -- metric icons live in a keyed parent tuple */
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertCircle, ArrowRight, Bell, CalendarClock, CheckCircle2, Clock3, ExternalLink, History, Loader2, Radar, Save, ShieldAlert, Sparkles, TrendingDown, TrendingUp, XCircle } from "lucide-react";
import { PageHeader } from "@/components/shared/page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select } from "@/components/ui/select";
import { PROVIDER_LABELS } from "@/features/real-ai-search/types";
import type { MonitoringCenterResponse, MonitoringFrequency, MonitoringScheduleView, NotificationView, ProviderMonitoringSummary } from "./types";

async function readJson<T>(response: Response): Promise<T> { const text = await response.text(); const body = text ? JSON.parse(text) as T & { error?: string } : {} as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "请求失败"); return body; }
const date = (value: string | null) => value ? new Date(value).toLocaleString("zh-CN") : "unavailable";
export function MonitoringCenterWorkspace({ projectId }: { projectId: string }) {
  const [data, setData] = useState<MonitoringCenterResponse | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => setData(await readJson<MonitoringCenterResponse>(await fetch(`/api/ai-search-monitoring/${projectId}`, { cache: "no-store" }))), [projectId]);
  useEffect(() => { let active = true; void load().catch((e) => { if (active) setError(e instanceof Error ? e.message : "监控中心加载失败"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [load]);
  async function saveSchedule(schedule: MonitoringScheduleView) { setSaving(true); setError(""); try { const result = await readJson<{ schedule: MonitoringScheduleView }>(await fetch(`/api/ai-search-monitoring/${projectId}/schedule`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: schedule.enabled, frequency: schedule.frequency, dailyTime: schedule.dailyTime, timezone: schedule.timezone }) })); setData((current) => current ? { ...current, schedule: result.schedule } : current); } catch (e) { setError(e instanceof Error ? e.message : "计划保存失败"); } finally { setSaving(false); } }
  if (loading) return <div className="flex min-h-72 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />正在读取真实 AI 搜索运营状态…</div>;
  if (!data) return <div className="rounded-2xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-destructive">Monitoring Center 加载失败：{error || "unavailable"}</div>;
  return <div data-testid="monitoring-center" className="min-w-0 space-y-6 overflow-x-hidden">
    <PageHeader title="AI Search Monitoring Center" description={`持续观察 ${data.project.name} 在四大 AI 平台中的品牌出现、推荐排名、引用和异常变化。`} action={<Button asChild variant="outline" className="min-h-11 w-full sm:w-auto"><Link href={`/projects/${projectId}/geo/monitoring`}>运行真实检测<ArrowRight className="h-4 w-4" /></Link></Button>} />
    {error ? <div className="flex gap-2 rounded-2xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div> : null}
    <OperationalPulse data={data} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.providers.map((provider) => <ProviderCard key={provider.provider} provider={provider} />)}</section>
    <section className="grid min-w-0 gap-6 xl:grid-cols-[0.85fr_1.15fr]"><ScheduleCard schedule={data.schedule} saving={saving} onSave={saveSchedule} /><ChangePanel changes={data.recentChanges} projectId={projectId} /></section>
    <section className="grid min-w-0 gap-6 xl:grid-cols-2"><HistoryPanel data={data} projectId={projectId} /><NotificationPanel data={data} projectId={projectId} /></section>
    <nav aria-label="监控中心后续模块" className="flex max-w-full gap-3 overflow-x-auto pb-2"><NextLink href={`/projects/${projectId}/geo/monitoring-center/history`} label="完整历史" /><NextLink href={`/projects/${projectId}/notifications`} label="通知中心" /><NextLink href={`/projects/${projectId}/geo/monitoring`} label="真实 AI 检测" /><NextLink href={`/projects/${projectId}/optimization`} label="优化中心" /></nav>
  </div>;
}
function OperationalPulse({ data }: { data: MonitoringCenterResponse }) { const items = [["最近一次检测", data.summary.lastCheckAt ? date(data.summary.lastCheckAt) : "unavailable", <Clock3 className="h-5 w-5" />], ["最近下降", `${data.summary.recentDrops}`, <TrendingDown className="h-5 w-5" />], ["最近提升", `${data.summary.recentImprovements}`, <TrendingUp className="h-5 w-5" />], ["待处理变化", `${data.summary.pendingChanges}`, <Bell className="h-5 w-5" />]] as const; return <Card className="glass-panel overflow-hidden border-cyan-300/20"><CardContent className="grid gap-4 p-5 lg:grid-cols-[0.7fr_0.3fr]"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{items.map(([label, value, icon]) => <div key={label} className="min-w-0 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><span className="text-cyan-300">{icon}</span><p className="mt-3 text-xs text-muted-foreground">{label}</p><p className="mt-1 break-words text-lg font-semibold">{value}</p></div>)}</div><div className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.04] p-4"><p className="flex items-center gap-2 text-sm font-medium text-amber-200"><ShieldAlert className="h-4 w-4" />Top Alert</p><p className="mt-3 text-sm font-semibold">{data.summary.topAlert?.title ?? "unavailable"}</p><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{data.summary.topAlert?.content ?? "尚无真实变化或 Provider 失败事件。"}</p></div></CardContent></Card>; }
function ProviderCard({ provider }: { provider: ProviderMonitoringSummary }) { return <Card className="glass-panel min-w-0 overflow-hidden border-white/10"><div className={`h-1 ${provider.status === "available" ? "bg-cyan-300" : "bg-white/10"}`} /><CardContent className="p-5"><div className="flex items-center justify-between gap-2"><Radar className="h-5 w-5 text-violet-300" /><Badge variant={provider.status === "available" ? "success" : "muted"}>{provider.status}</Badge></div><h2 className="mt-4 font-semibold">{PROVIDER_LABELS[provider.provider]}</h2><div className="mt-4 grid grid-cols-2 gap-2"><Metric label="最近检测" value={date(provider.latestCheckAt)} /><Metric label="最近成功" value={date(provider.latestSuccessAt)} /><Metric label="最近失败" value={date(provider.latestFailureAt)} /><Metric label="最近排名" value={provider.latestRank === null ? "unavailable" : `第 ${provider.latestRank} 位`} /><Metric label="最近引用" value={provider.latestCitationCount === null ? "unavailable" : `${provider.latestCitationCount}`} /><Metric label="品牌提及" value={provider.latestMentioned === null ? "unavailable" : provider.latestMentioned ? "已提及" : "未提及"} /></div><div className="mt-4 flex min-h-8 items-end gap-1" aria-label={`${provider.provider} 趋势`}>{provider.trend.length ? provider.trend.map((point) => <span key={point.resultId} title={`${date(point.completedAt)} · 排名 ${point.rankPosition ?? "unavailable"} · 引用 ${point.citationCount}`} className={`min-h-2 flex-1 rounded-sm ${point.mentioned ? "bg-emerald-300/70" : "bg-amber-300/60"}`} style={{ height: `${Math.max(8, Math.min(32, point.citationCount * 4 + 8))}px` }} />) : <span className="text-xs text-muted-foreground">趋势 unavailable</span>}</div></CardContent></Card>; }
function ScheduleCard({ schedule, saving, onSave }: { schedule: MonitoringScheduleView; saving: boolean; onSave: (schedule: MonitoringScheduleView) => Promise<void> }) { const [draft, setDraft] = useState(schedule); useEffect(() => setDraft(schedule), [schedule]); return <Card className="glass-panel min-w-0 border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="h-5 w-5 text-cyan-300" />Monitoring Schedule</CardTitle><p className="text-sm text-muted-foreground">仅保存运营计划，本阶段不会自动执行 Provider 请求。</p></CardHeader><CardContent className="space-y-4"><label className="flex min-h-11 items-center gap-3 rounded-xl border border-white/10 px-3 text-sm"><input type="checkbox" checked={draft.enabled} onChange={(event) => setDraft({ ...draft, enabled: event.target.checked })} />启用监控计划</label><div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="schedule-frequency">频率</Label><Select id="schedule-frequency" className="min-h-11" value={draft.frequency} onChange={(event) => setDraft({ ...draft, frequency: event.target.value as MonitoringFrequency })}><option value="DAILY">每天</option><option value="WEEKLY">每周</option><option value="MONTHLY">每月</option></Select></div><div className="space-y-2"><Label htmlFor="schedule-time">检测时间</Label><Input id="schedule-time" type="time" className="min-h-11" value={draft.dailyTime} onChange={(event) => setDraft({ ...draft, dailyTime: event.target.value })} /></div></div><div className="space-y-2"><Label htmlFor="schedule-timezone">时区</Label><Input id="schedule-timezone" className="min-h-11" value={draft.timezone} onChange={(event) => setDraft({ ...draft, timezone: event.target.value })} /></div><div className="rounded-xl border border-white/10 bg-white/[0.025] p-3 text-xs text-muted-foreground"><p>下次计划：{date(schedule.nextRunAt)}</p><p className="mt-1">上次运行：{date(schedule.lastRunAt)}</p></div><Button className="min-h-11 w-full sm:w-auto" disabled={saving} onClick={() => void onSave(draft)}>{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}保存监控计划</Button></CardContent></Card>; }
function ChangePanel({ changes, projectId }: { changes: NotificationView[]; projectId: string }) { return <Card className="glass-panel min-w-0 border-white/10"><CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-violet-300" />最近变化</CardTitle><p className="mt-2 text-sm text-muted-foreground">只展示真实前后轮比较产生的事件。</p></div><Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={`/projects/${projectId}/growth`}>Growth Timeline</Link></Button></CardHeader><CardContent className="space-y-3">{changes.length ? changes.map((item) => <AlertRow key={item.id} item={item} />) : <Empty text="没有可比较的上一轮真实结果，变化 unavailable。" />}</CardContent></Card>; }
function HistoryPanel({ data, projectId }: { data: MonitoringCenterResponse; projectId: string }) { return <Card className="glass-panel min-w-0 border-white/10"><CardHeader className="flex-row items-start justify-between gap-3"><CardTitle className="flex items-center gap-2"><History className="h-5 w-5 text-cyan-300" />Monitoring History</CardTitle><Button asChild variant="outline" className="min-h-11"><Link href={`/projects/${projectId}/geo/monitoring-center/history`}>筛选历史</Link></Button></CardHeader><CardContent className="space-y-3">{data.recentHistory.length ? data.recentHistory.slice(0, 5).map((item) => <div key={item.id} className="flex min-h-14 min-w-0 items-center gap-3 rounded-xl border border-white/10 p-3">{item.status === "SUCCEEDED" ? <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-300" /> : <XCircle className="h-4 w-4 shrink-0 text-rose-300" />}<span className="min-w-0 flex-1"><span className="block text-sm font-medium">{PROVIDER_LABELS[item.provider]} · {item.status}</span><span className="block truncate text-xs text-muted-foreground">{date(item.startedAt)} · {item.durationMs ?? "unavailable"}ms</span></span></div>) : <Empty text="尚无真实检测历史。" />}</CardContent></Card>; }
function NotificationPanel({ data, projectId }: { data: MonitoringCenterResponse; projectId: string }) { return <Card className="glass-panel min-w-0 border-white/10"><CardHeader className="flex-row items-start justify-between gap-3"><CardTitle className="flex items-center gap-2"><Bell className="h-5 w-5 text-amber-300" />站内通知</CardTitle><Button asChild variant="outline" className="min-h-11"><Link href={`/projects/${projectId}/notifications`}>通知中心</Link></Button></CardHeader><CardContent className="space-y-3">{data.notifications.length ? data.notifications.slice(0, 5).map((item) => <AlertRow key={item.id} item={item} />) : <Empty text="暂无真实监控通知。" />}</CardContent></Card>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-white/10 p-2"><p className="text-[10px] text-muted-foreground">{label}</p><p className="mt-1 break-words text-xs font-medium">{value}</p></div>; }
function AlertRow({ item }: { item: NotificationView }) { return <div className="min-w-0 rounded-xl border border-white/10 bg-white/[0.025] p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant={item.level === "HIGH" ? "warning" : "outline"}>{item.level}</Badge><Badge variant={item.isRead ? "muted" : "success"}>{item.isRead ? "已读" : "未读"}</Badge></div><p className="mt-2 break-words text-sm font-semibold">{item.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-muted-foreground">{item.content}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-white/15 p-4 text-sm text-muted-foreground">{text}</div>; }
function NextLink({ href, label }: { href: string; label: string }) { return <Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={href}>{label}<ExternalLink className="h-4 w-4" /></Link></Button>; }
