"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Bot, BrainCircuit, CircleDot, FileText, LineChart, ListChecks, Loader2, SearchCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import type { GrowthReportDetail, SnapshotModule } from "./types";

const modules: Array<[Exclude<keyof GrowthReportDetail["snapshot"], "reportMeta">, string, string]> = [
  ["seoSnapshot", "SEO 增长状态", "网站健康、技术与内容证据"], ["geoSnapshot", "GEO AI 搜索状态", "实体、可见性与 GEO 问题"], ["aiSearchSnapshot", "AI 推荐表现", "真实检测、引用与增长评分"], ["knowledgeSnapshot", "知识资产完整度", "企业画像与知识资产"], ["competitorSnapshot", "竞品差距", "最近一次真实 Benchmark"], ["optimizationSnapshot", "增长机会", "问题与统一优化任务"], ["insightSnapshot", "洞察中心", "生成时的诊断洞察"], ["roadmapSnapshot", "执行路线图", "优先任务与历史增长节点"],
];
function displayDate(value: string) { return new Intl.DateTimeFormat("zh-CN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function Summary({ value }: { value: SnapshotModule }) {
  if (value.status === "unavailable") return <p className="text-sm text-muted-foreground">unavailable：生成时没有可验证数据。</p>;
  const highlights = Object.entries(value.data ?? {}).filter(([, item]) => typeof item === "number" || typeof item === "string" || item === null).slice(0, 6);
  return <div className="space-y-3"><div className="flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-emerald-200">{value.evidenceStatus}</span>{value.sourceType.map((source) => <span key={source} className="rounded-full border border-white/10 px-2.5 py-1 text-muted-foreground">{source}</span>)}</div>{highlights.length ? <dl className="grid gap-2 sm:grid-cols-2">{highlights.map(([key, item]) => <div key={key} className="rounded-xl bg-white/[0.03] p-3"><dt className="text-xs text-muted-foreground">{key}</dt><dd className="mt-1 break-words text-sm font-medium">{item === null ? "unavailable" : String(item)}</dd></div>)}</dl> : <p className="text-sm text-muted-foreground">完整证据已固化在本报告快照中。</p>}</div>;
}

export function GrowthReportDetailView({ projectId, reportId }: { projectId: string; reportId: string }) {
  const [report, setReport] = useState<GrowthReportDetail | null>(null); const [error, setError] = useState(false);
  useEffect(() => { let current = true; void fetch(`/api/projects/${projectId}/reports/${reportId}`, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(); return response.json() as Promise<{ report: GrowthReportDetail }>; }).then((payload) => { if (current) setReport(payload.report); }).catch(() => { if (current) setError(true); }); return () => { current = false; }; }, [projectId, reportId]);
  if (error) return <Card><CardContent className="space-y-4 p-6"><p>无法读取这份报告，或当前账号没有访问权限。</p><Button asChild className="min-h-11"><Link href={`/projects/${projectId}/reports`}>返回报告列表</Link></Button></CardContent></Card>;
  if (!report) return <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div>;
  const meta = report.snapshot.reportMeta;
  return <div className="min-w-0 space-y-6 overflow-x-hidden" data-testid="growth-report-detail">
    <Button asChild variant="ghost" className="min-h-11"><Link href={`/projects/${projectId}/reports`}><ArrowLeft className="mr-2 h-4 w-4" />返回历史报告</Link></Button>
    <section className="rounded-3xl border border-violet-400/20 bg-[radial-gradient(circle_at_top_right,rgba(139,92,246,0.18),transparent_45%),linear-gradient(135deg,rgba(15,23,42,0.98),rgba(2,6,23,0.98))] p-5 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-violet-200">只读历史快照 · Report v{meta.version}</p><h1 className="mt-2 text-2xl font-semibold text-white sm:text-3xl">{meta.projectName} AI 增长报告</h1><p className="mt-2 text-sm text-slate-300">生成于 {displayDate(meta.generatedAt)} · {meta.domain}</p></div><div className="flex flex-col gap-3"><div className="grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-white/[0.06] p-3"><span className="block text-xs text-slate-400">证据覆盖</span><strong>{meta.confidence}%</strong></div><div className="rounded-xl bg-white/[0.06] p-3"><span className="block text-xs text-slate-400">状态</span><strong>{meta.status}</strong></div></div><Button asChild className="min-h-11 gap-2"><Link href={`/projects/${projectId}/growth/actions?generate=1&reportId=${report.id}`}><CircleDot className="h-4 w-4" />开始执行本报告</Link></Button><Button asChild variant="outline" className="min-h-11 gap-2"><Link href={`/projects/${projectId}/growth/agent?generate=1&reportId=${report.id}`}><BrainCircuit className="h-4 w-4" />生成 AI Growth Agent</Link></Button></div></div></section>
    <Card><CardHeader><CardTitle>管理层摘要</CardTitle><CardDescription>完全基于生成时的真实证据，以规则方式归纳。</CardDescription></CardHeader><CardContent className="grid gap-5 lg:grid-cols-2"><div><h3 className="mb-2 text-sm font-medium">当前状态</h3>{meta.executiveSummary.currentState.length ? <ul className="space-y-2 text-sm text-muted-foreground">{meta.executiveSummary.currentState.map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="text-sm text-muted-foreground">unavailable</p>}</div><div><h3 className="mb-2 text-sm font-medium">优先动作</h3>{meta.executiveSummary.priorities.length ? <ol className="space-y-2 text-sm text-muted-foreground">{meta.executiveSummary.priorities.map((item, index) => <li key={item}>{index + 1}. {item}</li>)}</ol> : <p className="text-sm text-muted-foreground">unavailable</p>}</div></CardContent></Card>
    <div className="grid gap-4 xl:grid-cols-2">{modules.map(([key, title, description]) => <Card key={key} className="min-w-0"><CardHeader><div className="flex items-center justify-between gap-3"><div><CardTitle className="text-base">{title}</CardTitle><CardDescription>{description}</CardDescription></div><span className="shrink-0 text-xs text-muted-foreground">{report.snapshot[key].status}</span></div></CardHeader><CardContent><Summary value={report.snapshot[key]} /></CardContent></Card>)}</div>
    <Card><CardHeader><CardTitle>HTML 报告预览</CardTitle><CardDescription>预览内容只来自已保存的 snapshot；本阶段不生成 PDF/PPT 文件。</CardDescription></CardHeader><CardContent><iframe title={`Report v${meta.version} HTML 预览`} sandbox="" srcDoc={report.htmlPreview} className="h-[520px] w-full rounded-xl border bg-white" /></CardContent></Card>
    <section aria-label="相关增长模块" className="overflow-hidden"><div className="flex snap-x snap-mandatory gap-3 overflow-x-auto overscroll-x-contain pb-2"><ModuleLink href={`/projects/${projectId}/growth/agent`} icon={BrainCircuit} title="AI Growth Agent" subtitle="查看执行方案" /><ModuleLink href={`/projects/${projectId}/growth/actions`} icon={CircleDot} title="AI Growth Action Center" subtitle="执行本报告行动" /><ModuleLink href={`/projects/${projectId}/growth`} icon={LineChart} title="Growth Timeline" subtitle="查看增长时间线" /><ModuleLink href={`/projects/${projectId}/optimization`} icon={ListChecks} title="Optimization Center" subtitle="执行优化任务" /><ModuleLink href={`/projects/${projectId}/geo/command-center`} icon={Bot} title="AI Search Command Center" subtitle="查看当前 AI 搜索状态" /><ModuleLink href={`/projects/${projectId}/seo`} icon={SearchCheck} title="SEO Growth" subtitle="进入 SEO 增长模块" /></div></section>
  </div>;
}
function ModuleLink({ href, icon: Icon, title, subtitle }: { href: string; icon: typeof FileText; title: string; subtitle: string }) { return <Link href={href} className="group flex min-h-24 w-[280px] shrink-0 snap-start items-center gap-3 rounded-2xl border border-white/10 bg-card p-4 transition hover:border-primary/40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Icon className="h-5 w-5 shrink-0 text-primary" /><span className="min-w-0"><strong className="block text-sm">{title}</strong><span className="mt-1 block text-xs text-muted-foreground">{subtitle}</span></span><ArrowRight className="ml-auto h-4 w-4 shrink-0 transition group-hover:translate-x-1" /></Link>; }
