import assert from "node:assert/strict";
import test from "node:test";
import { buildGrowthActionCandidates } from "./growth-action-generator";
import type { GrowthReportSnapshot, SnapshotModule } from "@/features/growth-reports/types";

const unavailable = (): SnapshotModule => ({ status: "unavailable", sourceId: [], sourceType: [], generatedAt: "2026-07-22T00:00:00.000Z", evidenceStatus: "unavailable" });
function snapshot(optimizationData?: Record<string, unknown>, aiData?: Record<string, unknown>): GrowthReportSnapshot { return { reportMeta: { projectId: "p1", projectName: "Test", domain: "example.com", version: 1, generatedBy: "u1", generatedAt: "2026-07-22T00:00:00.000Z", dataVersion: "v1", methodVersion: "v1", confidence: 50, status: "COMPLETED", executiveSummary: { status: "available", currentState: [], priorities: [] } }, seoSnapshot: unavailable(), geoSnapshot: unavailable(), aiSearchSnapshot: aiData ? { ...unavailable(), status: "available", evidenceStatus: "verified", data: aiData } : unavailable(), knowledgeSnapshot: unavailable(), competitorSnapshot: unavailable(), optimizationSnapshot: optimizationData ? { ...unavailable(), status: "available", evidenceStatus: "verified", data: optimizationData } : unavailable(), insightSnapshot: unavailable(), roadmapSnapshot: unavailable() }; }

test("有真实任务证据时生成行动并映射分类", () => { const result = buildGrowthActionCandidates(snapshot({ tasks: [{ id: "task-1", title: "补充客户案例", recommendation: "录入可验证客户结果", severity: "High", category: "knowledge", status: "PENDING" }] })); assert.equal(result.length, 1); assert.equal(result[0]?.optimizationTaskId, "task-1"); assert.equal(result[0]?.priority, "HIGH"); });
test("无证据返回空集合（业务层呈现 unavailable）", () => assert.deepEqual(buildGrowthActionCandidates(snapshot()), []));
test("没有报告时仍可使用当前真实 OptimizationTask", () => { const result = buildGrowthActionCandidates(null, [{ id: "live-1", title: "完善 Schema", recommendation: "添加真实结构化数据", severity: "Medium", category: "schema", status: "PENDING" }]); assert.equal(result[0]?.sourceKey, "optimization:live-1"); });
test("相同证据不会生成重复行动", () => { const task = { id: "task-1", title: "修复标题", recommendation: "补齐页面标题", severity: "Medium", category: "seo", status: "PENDING" }; const result = buildGrowthActionCandidates(snapshot({ tasks: [task, task] })); assert.equal(result.length, 1); assert.equal(result[0]?.sourceKey, "optimization:task-1"); });
test("只有真实成功检测才产生可见性与引用行动", () => { assert.equal(buildGrowthActionCandidates(snapshot(undefined, { results: [{ id: "r1", status: "FAILED", mentioned: false }], citationCount: 0 })).length, 0); const result = buildGrowthActionCandidates(snapshot(undefined, { results: [{ id: "r2", status: "SUCCEEDED", mentioned: false }], citationCount: 0 })); assert.deepEqual(result.map((item) => item.sourceType).sort(), ["CITATION_GAP", "REAL_AI_VISIBILITY_GAP"]); });
