import { realAISearchDatabase, type Row } from "@/features/real-ai-search/database";
import type { GrowthActionCandidate, GrowthActionStatus, GrowthActionView } from "./types";

const iso = (value: unknown) => value ? new Date(String(value)).toISOString() : null;
function view(row: Row): GrowthActionView { return { id: String(row.id), projectId: String(row.projectId), opportunityId: row.opportunityId ? String(row.opportunityId) : null, optimizationTaskId: row.optimizationTaskId ? String(row.optimizationTaskId) : null, sourceKey: String(row.sourceKey), sourceType: String(row.sourceType), title: String(row.title), description: String(row.description), category: String(row.category) as GrowthActionView["category"], priority: String(row.priority) as GrowthActionView["priority"], status: String(row.status) as GrowthActionStatus, impact: String(row.impact) as GrowthActionView["impact"], createdBy: String(row.createdBy), completedAt: iso(row.completedAt), verifiedAt: iso(row.verifiedAt), createdAt: iso(row.createdAt) ?? new Date(0).toISOString() }; }

export const growthActionRepository = {
  async projectOwned(userId: string, projectId: string) { return Boolean((await realAISearchDatabase().query('SELECT 1 FROM "Project" WHERE "id" = $1 AND "userId" = $2', [projectId, userId]))[0]); },
  async latestReport(userId: string, projectId: string, reportId?: string) { return (await realAISearchDatabase().query(`SELECT report.* FROM "GrowthReport" report INNER JOIN "Project" p ON p."id" = report."projectId" WHERE report."projectId" = $1 AND p."userId" = $2 AND report."status" = 'COMPLETED'::"GrowthReportStatus" ${reportId ? 'AND report."id" = $3' : ''} ORDER BY report."version" DESC LIMIT 1`, reportId ? [projectId, userId, reportId] : [projectId, userId]))[0] ?? null; },
  async currentTasks(userId: string, projectId: string) { return realAISearchDatabase().query('SELECT task.* FROM "OptimizationTask" task INNER JOIN "Project" p ON p."id" = task."projectId" WHERE task."projectId" = $1 AND p."userId" = $2 AND task."status" <> \'COMPLETED\' ORDER BY task."updatedAt" DESC LIMIT 200', [projectId, userId]); },
  async list(userId: string, projectId: string) { const result = await realAISearchDatabase().query('SELECT action.* FROM "GrowthAction" action INNER JOIN "Project" p ON p."id" = action."projectId" WHERE action."projectId" = $1 AND p."userId" = $2 ORDER BY CASE action."status" WHEN \'IN_PROGRESS\' THEN 1 WHEN \'TODO\' THEN 2 WHEN \'COMPLETED\' THEN 3 ELSE 4 END, CASE action."priority" WHEN \'HIGH\' THEN 1 WHEN \'MEDIUM\' THEN 2 ELSE 3 END, action."createdAt" DESC', [projectId, userId]); return result.map(view); },
  async insert(userId: string, projectId: string, candidates: GrowthActionCandidate[]) { let created = 0; for (const item of candidates) { const row = (await realAISearchDatabase().query('INSERT INTO "GrowthAction" ("id", "projectId", "opportunityId", "optimizationTaskId", "sourceKey", "sourceType", "title", "description", "category", "priority", "status", "impact", "createdBy", "createdAt") SELECT $1, p."id", $4, task."id", $5, $6, $7, $8, $9::"GrowthActionCategory", $10::"GrowthActionPriority", \'TODO\'::"GrowthActionStatus", $11::"GrowthActionImpact", $2, $12 FROM "Project" p LEFT JOIN "OptimizationTask" task ON task."id" = $3 AND task."projectId" = p."id" WHERE p."id" = $13 AND p."userId" = $2 ON CONFLICT ("projectId", "sourceKey") DO NOTHING RETURNING "GrowthAction".*', [crypto.randomUUID(), userId, item.optimizationTaskId, item.opportunityId, item.sourceKey, item.sourceType, item.title, item.description, item.category, item.priority, item.impact, new Date(), projectId]))[0]; if (row) created += 1; } return created; },
  async updateStatus(userId: string, projectId: string, actionId: string, status: GrowthActionStatus) { const now = new Date(); const row = (await realAISearchDatabase().query('UPDATE "GrowthAction" action SET "status" = $4::"GrowthActionStatus", "completedAt" = CASE WHEN $4 IN (\'COMPLETED\', \'VERIFIED\') THEN COALESCE(action."completedAt", $5) ELSE action."completedAt" END, "verifiedAt" = CASE WHEN $4 = \'VERIFIED\' THEN COALESCE(action."verifiedAt", $5) ELSE action."verifiedAt" END FROM "Project" p WHERE action."id" = $1 AND action."projectId" = $2 AND action."projectId" = p."id" AND p."userId" = $3 RETURNING action.*', [actionId, projectId, userId, status, now]))[0]; return row ? view(row) : null; },
  async timeline(userId: string, action: GrowthActionView) { await realAISearchDatabase().query('INSERT INTO "GrowthSnapshot" ("id", "projectId", "eventType", "triggerType", "sourceId", "metadata", "createdAt") SELECT $1, p."id", \'OPTIMIZATION\'::"GrowthEventType", \'AUTO\'::"GrowthTriggerType", $3, $4::jsonb, $5 FROM "Project" p WHERE p."id" = $2 AND p."userId" = $6 ON CONFLICT ("projectId", "eventType", "sourceId") DO NOTHING', [crypto.randomUUID(), action.projectId, `growth-action:${action.id}:completed`, JSON.stringify({ growthActionId: action.id, title: action.title, category: action.category, sourceType: action.sourceType, opportunityId: action.opportunityId, optimizationTaskId: action.optimizationTaskId, completedAt: action.completedAt }), new Date(action.completedAt ?? Date.now()), userId]); },
};
