"use client";

import Link from "next/link";
import { useCallback, useEffect, useState, type ReactNode } from "react";
import { AlertCircle, ArrowRight, BarChart3, Bot, BrainCircuit, CheckCircle2, CircleDashed, ExternalLink, FileSearch, Gauge, Loader2, Medal, Network, Quote, RefreshCw, Search, ShieldCheck, Sparkles, Target, TrendingUp } from "lucide-react";
import { PageHeader } from "@/components/shared/page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { PROVIDER_LABELS } from "@/features/real-ai-search/types";
import type { AISearchGrowthResponse, CompetitionMetric, RecommendationExplanationReason } from "./types";

async function readJson<T>(response: Response): Promise<T> { const text = await response.text(); const body = text ? JSON.parse(text) as T & { error?: string } : {} as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "请求失败"); return body; }
const unavailable = <span className="text-sm font-medium text-muted-foreground">unavailable</span>;

export function AISearchCommandCenter({ projectId }: { projectId: string }) {
  const [data, setData] = useState<AISearchGrowthResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [calculating, setCalculating] = useState(false);
  const [error, setError] = useState("");
  const load = useCallback(async () => setData(await readJson<AISearchGrowthResponse>(await fetch(`/api/ai-search-growth/${projectId}`, { cache: "no-store" }))), [projectId]);
  useEffect(() => { let active = true; void load().catch((requestError) => { if (active) setError(requestError instanceof Error ? requestError.message : "增长数据加载失败"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [load]);
  async function calculate() { setCalculating(true); setError(""); try { setData(await readJson<AISearchGrowthResponse>(await fetch(`/api/ai-search-growth/${projectId}`, { method: "POST" }))); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "评分计算失败"); } finally { setCalculating(false); } }
  if (loading) return <div className="flex min-h-72 items-center justify-center gap-2 text-sm text-muted-foreground"><Loader2 className="h-4 w-4 animate-spin" />正在汇总企业 AI 搜索增长证据…</div>;
  if (!data) return <div className="rounded-2xl border border-destructive/30 bg-destructive/10 p-5 text-sm text-destructive">AI 搜索增长驾驶舱加载失败：{error || "暂无数据"}</div>;
  return <div data-testid="ai-command-center" className="min-w-0 space-y-6 overflow-x-hidden">
    <PageHeader title="AI 搜索增长驾驶舱" description={`把 ${data.project.name} 在 AI 平台中的出现、引用、排名、竞争差距与下一步行动放在同一个商业视图中。`} action={<Button asChild variant="outline" className="min-h-11 w-full sm:w-auto"><Link href={`/projects/${projectId}/geo/monitoring`}>真实 AI 检测 <ArrowRight className="h-4 w-4" /></Link></Button>} />
    {error ? <div className="flex gap-2 rounded-2xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div> : null}
    <GrowthScoreHero data={data} calculating={calculating} onCalculate={() => void calculate()} />
    <VisibilityOverview data={data} />
    <RecommendationTrend data={data} />
    <CompetitionComparison data={data} />
    <section className="grid min-w-0 gap-6 xl:grid-cols-[0.9fr_1.1fr]"><ExplanationPanel data={data} /><RoadmapPanel data={data} /></section>
    <GrowthRelationship data={data} />
    <nav aria-label="AI 搜索增长后续模块" className="flex max-w-full gap-3 overflow-x-auto pb-2"><NextLink href={`/projects/${projectId}/geo/monitoring`} label="真实 AI 检测" /><NextLink href={`/projects/${projectId}/geo/intelligence`} label="推荐诊断" /><NextLink href={`/projects/${projectId}/optimization`} label="优化中心" /></nav>
  </div>;
}

function GrowthScoreHero({ data, calculating, onCalculate }: { data: AISearchGrowthResponse; calculating: boolean; onCalculate: () => void }) {
  const score = data.score;
  const metrics = [["AI 搜索健康度", score.visibilityScore, "真实品牌出现率"], ["引用能力", score.citationScore, "成功回答引用覆盖"], ["知识完整度", score.knowledgeScore, "企业证据资产"], ["品牌可信度", score.authorityScore, "企业实体完整度"], ["竞争优势", score.competitionScore, "相对最强竞品"]] as const;
  return <Card className="glass-panel relative overflow-hidden border-violet-300/20"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_10%_0%,rgba(167,139,250,0.16),transparent_42%),radial-gradient(circle_at_88%_100%,rgba(34,211,238,0.09),transparent_36%)]" /><CardContent className="relative grid gap-6 p-5 sm:p-7 xl:grid-cols-[0.32fr_0.68fr]"><div className="flex min-w-0 flex-col justify-between rounded-3xl border border-violet-300/20 bg-background/45 p-5"><div><p className="flex items-center gap-2 text-sm font-medium text-violet-200"><Gauge className="h-5 w-5" />企业 AI 增长健康度</p>{score.overallScore === null ? <p className="mt-5 text-2xl font-semibold text-muted-foreground">unavailable</p> : <p className="mt-4 text-6xl font-semibold tracking-tight text-violet-100">{score.overallScore}<span className="ml-1 text-base text-muted-foreground">/100</span></p>}<p className="mt-3 text-xs leading-5 text-muted-foreground">证据可信度 {score.confidence}% · 固定权重，不对缺失数据重新归一化</p></div><Button className="mt-5 min-h-11 w-full" disabled={calculating || score.status === "unavailable"} onClick={onCalculate}>{calculating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />}保存本次增长评分</Button></div><div className="grid min-w-0 gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label, value, detail]) => <div key={label} className="min-w-0 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-3 text-2xl font-semibold">{value === null ? "—" : value}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{value === null ? "unavailable" : detail}</p>{value !== null ? <Progress value={value} className="mt-3" /> : null}</div>)}</div></CardContent></Card>;
}

function VisibilityOverview({ data }: { data: AISearchGrowthResponse }) {
  return <section className="space-y-4"><SectionHeading eyebrow="AI Visibility" title="企业在 AI 回答中的真实出现情况" description="只统计成功完成的真实 Provider 检测；失败和规则模拟不会进入指标。" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{data.overview.providers.map((provider) => <Card key={provider.provider} className="glass-panel min-w-0 border-white/10"><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><Bot className="h-5 w-5 text-violet-300" /><Badge variant={provider.status === "available" ? "success" : "muted"}>{provider.status}</Badge></div><h3 className="mt-4 font-semibold">{PROVIDER_LABELS[provider.provider]}</h3><div className="mt-4 grid grid-cols-3 gap-2"><MiniMetric label="出现" value={provider.mentionCount} /><MiniMetric label="引用" value={provider.citationCount} /><MiniMetric label="平均排名" value={provider.averageRank} /></div><p className="mt-3 text-xs text-muted-foreground">成功检测 {provider.successfulChecks} 次</p></CardContent></Card>)}</div><div className="grid gap-3 sm:grid-cols-3"><SummaryCard icon={<Sparkles className="h-5 w-5" />} label="品牌提及次数" value={data.overview.brandMentions} /><SummaryCard icon={<Quote className="h-5 w-5" />} label="引用总数" value={data.overview.citations} /><SummaryCard icon={<Medal className="h-5 w-5" />} label="推荐排名平均值" value={data.overview.averageRank} /></div></section>;
}

function RecommendationTrend({ data }: { data: AISearchGrowthResponse }) {
  return <Card className="glass-panel min-w-0 border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><TrendingUp className="h-5 w-5 text-cyan-300" />AI 推荐趋势</CardTitle><p className="text-sm text-muted-foreground">按真实检测完成时间展示品牌出现、排名与引用变化。</p></CardHeader><CardContent>{data.trend.length ? <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data.trend.slice(-12).map((point) => <article key={point.id} className="min-w-0 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex items-center justify-between gap-2"><Badge variant="outline">{PROVIDER_LABELS[point.provider]}</Badge>{point.mentioned ? <CheckCircle2 className="h-4 w-4 text-emerald-300" /> : <CircleDashed className="h-4 w-4 text-amber-300" />}</div><p className="mt-3 text-sm font-medium">{point.mentioned ? "品牌已出现" : "品牌未出现"}</p><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground"><span>排名 {point.rankPosition ?? "unavailable"}</span><span>引用 {point.citationCount}</span></div><p className="mt-3 text-xs text-muted-foreground">{new Date(point.completedAt).toLocaleString("zh-CN")}</p></article>)}</div> : <EmptyEvidence text="尚无成功的真实 AI 检测结果，推荐趋势 unavailable。" />}</CardContent></Card>;
}

function CompetitionComparison({ data }: { data: AISearchGrowthResponse }) {
  return <section className="space-y-4"><SectionHeading eyebrow="Competitive Intelligence" title="目标企业与竞品的 AI 推荐能力对比" description="每项指标独立检查证据；当前模型无法归属到具体竞品的 Citation 不会被推测填充。" /><div className="grid min-w-0 gap-4 lg:grid-cols-2">{data.competition.rows.map((row) => <Card key={`${row.targetType}-${row.id}`} className={`glass-panel min-w-0 ${row.targetType === "OWN" ? "border-violet-300/30" : "border-white/10"}`}><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Badge variant={row.targetType === "OWN" ? "success" : "outline"}>{row.targetType === "OWN" ? "目标企业" : "竞品企业"}</Badge><h3 className="mt-3 break-words text-lg font-semibold">{row.name}</h3></div><Medal className={`h-5 w-5 shrink-0 ${row.targetType === "OWN" ? "text-violet-300" : "text-muted-foreground"}`} /></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-5"><ComparisonCell label="品牌出现率" metric={row.appearanceRate} /><ComparisonCell label="Citation 数量" metric={row.citationCount} /><ComparisonCell label="产品覆盖" metric={row.productCoverage} /><ComparisonCell label="知识完整度" metric={row.knowledgeCompleteness} /><ComparisonCell label="推荐概率" metric={row.recommendationProbability} /></div></CardContent></Card>)}</div></section>;
}

function ExplanationPanel({ data }: { data: AISearchGrowthResponse }) {
  return <Card className="glass-panel min-w-0 border-white/10"><CardHeader><CardTitle className="flex items-center gap-2"><BrainCircuit className="h-5 w-5 text-violet-300" />为什么 AI 没有推荐企业</CardTitle><p className="text-sm text-muted-foreground">严格证据模式，每个结论都能回溯到项目数据。</p></CardHeader><CardContent className="space-y-3">{data.explanation.status === "unavailable" ? <EmptyEvidence text={data.explanation.unavailableReason ?? "解释 unavailable。"} /> : data.explanation.reasons.length ? data.explanation.reasons.map((reason) => <ReasonCard key={reason.type} reason={reason} />) : <div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.04] p-4 text-sm text-emerald-100">当前证据未发现达到规则阈值的 AI 推荐阻碍。</div>}</CardContent></Card>;
}

function RoadmapPanel({ data }: { data: AISearchGrowthResponse }) {
  return <Card className="glass-panel min-w-0 border-white/10"><CardHeader className="flex-row items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2"><Target className="h-5 w-5 text-amber-300" />AI Growth Roadmap</CardTitle><p className="mt-2 text-sm text-muted-foreground">从现有统一优化任务中按优先级整理 Top 10。</p></div><Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={`/projects/${data.project.id}/optimization`}>执行任务</Link></Button></CardHeader><CardContent className="space-y-3">{data.roadmap.length ? data.roadmap.map((task, index) => <Link key={task.id} href={`/projects/${data.project.id}/optimization?issueId=${encodeURIComponent(task.issueId)}`} className="flex min-h-16 min-w-0 items-start gap-3 rounded-2xl border border-white/10 bg-white/[0.025] p-4 transition hover:border-amber-300/30"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-amber-300/10 text-xs font-semibold text-amber-200">{index + 1}</span><span className="min-w-0 flex-1"><span className="flex flex-wrap gap-2"><Badge variant={task.priority === "HIGH" ? "warning" : "outline"}>{task.priority}</Badge><Badge variant="muted">{task.source}</Badge></span><span className="mt-2 block break-words text-sm font-semibold">{task.title}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{task.impact} · {task.recommendation}</span></span><ArrowRight className="mt-2 h-4 w-4 shrink-0 text-muted-foreground" /></Link>) : <EmptyEvidence text="当前没有来自真实可见性、推荐诊断、知识或竞品差距的优化任务。" />}</CardContent></Card>;
}

function GrowthRelationship({ data }: { data: AISearchGrowthResponse }) {
  const stages = [{ label: "网站结构、关键词、内容", title: "SEO 让搜索引擎理解", ready: data.relationship.websiteScanAvailable || data.relationship.seoAnalysisAvailable, icon: Search }, { label: "知识画像与企业实体", title: "GEO 让 AI 理解", ready: data.relationship.knowledgeProfileAvailable, icon: Network }, { label: "品牌出现、引用与排名", title: "AI 形成推荐", ready: data.relationship.realAISearchAvailable, icon: ShieldCheck }];
  return <Card className="glass-panel overflow-hidden border-cyan-300/20"><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-cyan-300" />Growth Relationship</CardTitle><p className="text-sm text-muted-foreground">SEO 的可抓取内容成为 GEO 的企业知识证据，最终影响 AI 推荐与 Citation。</p></CardHeader><CardContent><div className="grid gap-3 lg:grid-cols-[1fr_auto_1fr_auto_1fr] lg:items-center">{stages.map((stage, index) => { const Icon = stage.icon; return <div key={stage.title} className="contents"><div className="min-w-0 rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="flex items-center justify-between gap-3"><Icon className="h-5 w-5 text-cyan-300" /><Badge variant={stage.ready ? "success" : "muted"}>{stage.ready ? "已有证据" : "待建立"}</Badge></div><p className="mt-4 font-semibold">{stage.title}</p><p className="mt-2 text-sm text-muted-foreground">{stage.label}</p></div>{index < stages.length - 1 ? <ArrowRight className="mx-auto h-5 w-5 rotate-90 text-cyan-300 lg:rotate-0" /> : null}</div>; })}</div></CardContent></Card>;
}

function SectionHeading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">{eyebrow}</p><h2 className="mt-2 text-xl font-semibold tracking-tight">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div>; }
function MiniMetric({ label, value }: { label: string; value: number | null }) { return <div className="min-w-0 rounded-xl border border-white/10 p-2 text-center"><p className="text-lg font-semibold">{value ?? "—"}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{value === null ? "unavailable" : label}</p></div>; }
function SummaryCard({ icon, label, value }: { icon: ReactNode; label: string; value: number | null }) { return <Card className="glass-panel min-w-0 border-white/10"><CardContent className="flex min-h-24 items-center gap-4 p-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-primary/20 bg-primary/10 text-primary">{icon}</span><span><span className="block text-xs text-muted-foreground">{label}</span><span className="mt-1 block text-2xl font-semibold">{value ?? "—"}</span>{value === null ? unavailable : null}</span></CardContent></Card>; }
function ComparisonCell({ label, metric }: { label: string; metric: CompetitionMetric }) { const suffix = metric.unit === "percent" ? "%" : ""; return <div className="min-w-0 rounded-xl border border-white/10 p-3 text-center"><p className="text-[11px] text-muted-foreground">{label}</p><p className="mt-2 break-words text-sm font-semibold">{metric.status === "available" ? `${metric.value}${suffix}` : "unavailable"}</p></div>; }
function ReasonCard({ reason }: { reason: RecommendationExplanationReason }) { return <article className="min-w-0 rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex flex-wrap gap-2"><Badge variant={reason.severity === "HIGH" ? "warning" : "outline"}>{reason.severity}</Badge><Badge variant="muted">{reason.type}</Badge></div><p className="mt-3 text-sm font-medium">{reason.description}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">建议：{reason.recommendation}</p><p className="mt-3 flex items-center gap-1 text-xs text-muted-foreground"><FileSearch className="h-3.5 w-3.5" />{reason.sources.length} 条可追溯证据</p></article>; }
function EmptyEvidence({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-white/15 bg-white/[0.015] p-5 text-sm leading-6 text-muted-foreground">{text}</div>; }
function NextLink({ href, label }: { href: string; label: string }) { return <Button asChild variant="outline" className="min-h-11 shrink-0"><Link href={href}>{label}<ExternalLink className="h-4 w-4" /></Link></Button>; }
