"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, Bot, CheckCircle2, Circle, Loader2, Pause, Play, RotateCcw, ShieldCheck, Square, XCircle } from "lucide-react";
import { MetricHelp } from "@/components/shared/metric-help";
import { PageHeader } from "@/components/shared/page";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useI18n } from "@/i18n/provider";
import { AUTOMATION_MODES, type AutomationMode, type AutomationRunView, type AutomationStepView } from "./types";

async function json<T>(response: Response): Promise<T> { const text = await response.text(); const body = text ? JSON.parse(text) as T & { error?: string } : {} as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? "REQUEST_FAILED"); return body; }

const modeKeys: Record<AutomationMode, "safe" | "standard" | "expert"> = { SAFE: "safe", STANDARD: "standard", EXPERT: "expert" };
function stepCopy(step: AutomationStepView, locale: "zh" | "en") { const provider = step.stepKey.replace("TEST_PROVIDER_", ""); const map: Record<string, [string, string]> = { LOAD_EVIDENCE: ["读取当前项目证据", "Load current project evidence"], GENERATE_ACTIONS: ["生成增长行动", "Generate growth actions"], SYNC_OPTIMIZATION: ["同步优化任务", "Sync optimization tasks"], GENERATE_AGENT_TASKS: ["生成 Agent 执行计划", "Generate agent execution plans"], GENERATE_REPORT: ["固化增长报告", "Create an immutable growth report"], REFRESH_TIMELINE: ["记录增长时间线", "Record the growth timeline"], CAPTURE_AFTER: ["验证执行结果", "Verify execution results"] }; if (step.stepKey.startsWith("TEST_PROVIDER_")) return locale === "zh" ? `测试 ${provider} 连接` : `Test ${provider} connection`; return map[step.stepKey]?.[locale === "zh" ? 0 : 1] ?? step.stepType; }
function activityCopy(step: AutomationStepView, locale: "zh" | "en") { const title = stepCopy(step, locale); if (step.status === "COMPLETED") return locale === "zh" ? `${title}已完成` : `${title} completed`; if (step.status === "FAILED") return locale === "zh" ? `${title}失败：${step.errorCode}` : `${title} failed: ${step.errorCode}`; if (step.status === "RUNNING") return locale === "zh" ? `正在${title}` : `${title} is running`; if (step.status === "AWAITING_APPROVAL") return locale === "zh" ? `${title}等待人工确认` : `${title} is awaiting approval`; return locale === "zh" ? `${title}等待执行` : `${title} is pending`; }

export function AutomationConsole({ projectId }: { projectId: string }) {
  const { locale, t } = useI18n();
  const [runs, setRuns] = useState<AutomationRunView[]>([]);
  const [run, setRun] = useState<AutomationRunView | null>(null);
  const [mode, setMode] = useState<AutomationMode>("SAFE");
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [autoAdvance, setAutoAdvance] = useState(false);
  const load = useCallback(async () => { const payload = await json<{ runs: AutomationRunView[] }>(await fetch(`/api/projects/${projectId}/automation`, { cache: "no-store" })); setRuns(payload.runs); setRun(current => current ? payload.runs.find(item => item.id === current.id) ?? payload.runs[0] ?? null : payload.runs[0] ?? null); }, [projectId]);
  useEffect(() => { void load().catch(requestError => setError(requestError instanceof Error ? requestError.message : "REQUEST_FAILED")); }, [load]);
  const advance = useCallback(async () => { if (!run || busy) return; setBusy("next"); try { const payload = await json<{ run: AutomationRunView }>(await fetch(`/api/projects/${projectId}/automation/${run.id}/next`, { method: "POST" })); setRun(payload.run); setRuns(current => [payload.run, ...current.filter(item => item.id !== payload.run.id)]); if (payload.run.status !== "RUNNING") setAutoAdvance(false); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "AUTOMATION_STEP_FAILED"); setAutoAdvance(false); await load().catch(() => undefined); } finally { setBusy(""); } }, [busy, load, projectId, run]);
  useEffect(() => { if (!autoAdvance || run?.status !== "RUNNING" || busy) return; const timer = window.setTimeout(() => void advance(), 800); return () => window.clearTimeout(timer); }, [advance, autoAdvance, busy, run?.status]);
  async function preview() { setBusy("preview"); setError(""); try { const payload = await json<{ run: AutomationRunView }>(await fetch(`/api/projects/${projectId}/automation/preview`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ mode }) })); setRun(payload.run); setRuns(current => [payload.run, ...current]); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "AUTOMATION_PREVIEW_FAILED"); } finally { setBusy(""); } }
  async function start() { if (!run) return; setBusy("start"); setError(""); try { const payload = await json<{ run: AutomationRunView }>(await fetch(`/api/projects/${projectId}/automation/${run.id}/start`, { method: "POST" })); setRun(payload.run); setAutoAdvance(true); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "AUTOMATION_START_FAILED"); } finally { setBusy(""); } }
  async function control(action: "pause" | "resume" | "cancel") { if (!run) return; setBusy(action); try { const payload = await json<{ run: AutomationRunView }>(await fetch(`/api/projects/${projectId}/automation/${run.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) })); setRun(payload.run); setAutoAdvance(action === "resume"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "AUTOMATION_CONTROL_FAILED"); } finally { setBusy(""); } }
  async function approve(step: AutomationStepView) { if (!run) return; setBusy(`approve:${step.id}`); try { const payload = await json<{ run: AutomationRunView }>(await fetch(`/api/projects/${projectId}/automation/${run.id}/steps/${step.id}/approve`, { method: "POST" })); setRun(payload.run); setAutoAdvance(true); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "AUTOMATION_APPROVAL_FAILED"); } finally { setBusy(""); } }
  const remaining = run?.steps.filter(step => ["PENDING", "AWAITING_APPROVAL"].includes(step.status)).length ?? 0;
  const completedDurations = run?.steps.flatMap(step => step.durationMs === null ? [] : [step.durationMs]) ?? [];
  const estimated = completedDurations.length ? Math.round(completedDurations.reduce((sum, value) => sum + value, 0) / completedDurations.length * remaining / 1000) : null;
  const comparison = useMemo(() => run?.afterSnapshot ? Object.entries(run.beforeSnapshot.metrics).map(([key, before]) => ({ key, before, after: run.afterSnapshot!.metrics[key as keyof typeof run.afterSnapshot.metrics] })) : [], [run]);
  const currentStep = run?.currentStepKey ? run.steps.find(step => step.stepKey === run.currentStepKey) : undefined;
  return <div className="min-w-0 space-y-6 overflow-x-hidden">
    <PageHeader title={t("automation.title")} description={t("automation.description")} action={<Button asChild variant="outline" className="min-h-11"><Link href={`/projects/${projectId}/growth/agent`}>{locale === "zh" ? "查看 Growth Agent" : "View Growth Agent"}<ArrowRight className="h-4 w-4" /></Link></Button>} />
    {error ? <div className="flex items-start gap-2 rounded-2xl border border-rose-400/30 bg-rose-400/10 p-4 text-sm text-rose-200"><XCircle className="mt-0.5 h-4 w-4 shrink-0" />{error}</div> : null}
    <Card className="overflow-hidden border-violet-300/20 bg-[radial-gradient(circle_at_top_right,rgba(139,92,246,.18),transparent_42%)]"><CardContent className="grid gap-5 p-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><div className="flex items-center gap-2 text-sm text-violet-200"><Bot className="h-5 w-5" />Auto + Human Approval</div><h2 className="mt-3 text-xl font-semibold">{locale === "zh" ? "先看清计划，再确认执行" : "Inspect the plan before execution"}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{t("automation.dryRunNotice")}</p><div className="mt-4 flex max-w-full gap-2 overflow-x-auto pb-1">{AUTOMATION_MODES.map(value => <button key={value} type="button" onClick={() => setMode(value)} className={`min-h-11 shrink-0 rounded-xl border px-4 text-sm ${mode === value ? "border-violet-300/40 bg-violet-300/15 text-violet-100" : "border-white/10 text-muted-foreground"}`}><span className="font-medium">{t(`automation.${modeKeys[value]}`)}</span><span className="ml-2 hidden text-xs opacity-70 md:inline">{t(`automation.${modeKeys[value]}Description`)}</span></button>)}</div></div><Button onClick={() => void preview()} disabled={busy !== ""} className="min-h-11 w-full lg:w-auto">{busy === "preview" ? <Loader2 className="h-4 w-4 animate-spin" /> : <ShieldCheck className="h-4 w-4" />}{t("automation.preview")}</Button></CardContent></Card>
    {run ? <>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label={t("automation.currentStatus")} value={run.status} /><Summary label={t("automation.currentStep")} value={currentStep ? stepCopy(currentStep, locale) : "—"} /><Summary label={t("automation.remainingSteps")} value={String(remaining)} /><Summary label={t("automation.estimatedTime")} value={estimated === null ? t("automation.unavailable") : `~${estimated}s`} /></section>
      <Card className="glass-panel border-white/10"><CardHeader><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><CardTitle>{t("automation.executionTimeline")}</CardTitle><p className="mt-2 text-sm text-muted-foreground">Run {run.id.slice(0, 8)} · {t(`automation.${modeKeys[run.mode]}`)}</p></div><div className="flex flex-wrap gap-2">{run.status === "PREVIEW" ? <Button className="min-h-11" onClick={() => void start()} disabled={busy !== ""}><Play className="h-4 w-4" />{t("automation.confirmStart")}</Button> : null}{run.status === "RUNNING" ? <Button variant="outline" className="min-h-11" onClick={() => void control("pause")}><Pause className="h-4 w-4" />{t("automation.pause")}</Button> : null}{run.status === "PAUSED" ? <Button className="min-h-11" onClick={() => void control("resume")}><RotateCcw className="h-4 w-4" />{t("automation.resume")}</Button> : null}{["PREVIEW", "RUNNING", "PAUSED", "AWAITING_APPROVAL"].includes(run.status) ? <Button variant="outline" className="min-h-11" onClick={() => void control("cancel")}><Square className="h-4 w-4" />{t("automation.cancel")}</Button> : null}</div></div></CardHeader><CardContent><div className="h-2 overflow-hidden rounded-full bg-white/[0.06]"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-emerald-300 transition-[width] duration-300 motion-reduce:transition-none" style={{ width: `${run.progress}%` }} /></div><div className="mt-5 grid gap-3">{run.steps.map(step => <StepRow key={step.id} step={step} locale={locale} busy={busy} onApprove={() => void approve(step)} />)}</div></CardContent></Card>
      <Card className="glass-panel border-white/10"><CardHeader><CardTitle>{t("automation.activityLog")}</CardTitle></CardHeader><CardContent className="grid gap-2">{run.steps.filter(step => step.startedAt || step.status === "AWAITING_APPROVAL").map(step => <div key={step.id} className="grid gap-1 rounded-xl border border-white/10 p-3 text-sm sm:grid-cols-[7rem_1fr]"><time className="text-xs text-muted-foreground">{step.startedAt ? new Date(step.startedAt).toLocaleTimeString(locale === "zh" ? "zh-CN" : "en-US") : "—"}</time><span>{activityCopy(step, locale)}</span></div>)}</CardContent></Card>
      {comparison.length ? <Card className="glass-panel border-emerald-300/20"><CardHeader><CardTitle>{t("automation.beforeAfter")}</CardTitle><p className="text-sm text-muted-foreground">{locale === "zh" ? "每个数值都保留真实 sourceId；缺少可比较数据时显示 Unavailable。" : "Every value retains its real sourceId. Missing comparable evidence remains unavailable."}</p></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{comparison.map(item => <MetricComparison key={item.key} item={item} locale={locale} />)}</CardContent></Card> : null}
      {run.summary ? <Card className="glass-panel border-violet-300/20"><CardHeader><CardTitle>{t("automation.impactSummary")}</CardTitle></CardHeader><CardContent><pre className="max-w-full overflow-x-auto whitespace-pre-wrap break-words rounded-2xl border border-white/10 bg-black/20 p-4 text-xs">{JSON.stringify(run.summary.records ?? run.summary, null, 2)}</pre></CardContent></Card> : null}
    </> : <Card className="glass-panel border-white/10"><CardContent className="p-8 text-center text-sm text-muted-foreground">{t("automation.noRun")}</CardContent></Card>}
    {runs.length > 1 ? <div className="flex max-w-full gap-2 overflow-x-auto pb-2" aria-label={locale === "zh" ? "历史执行" : "Run history"}>{runs.map(item => <button key={item.id} onClick={() => setRun(item)} className="min-h-11 shrink-0 rounded-xl border border-white/10 px-4 text-xs">{item.mode} · {item.status} · {new Date(item.createdAt).toLocaleString(locale === "zh" ? "zh-CN" : "en-US")}</button>)}</div> : null}
  </div>;
}

function Summary({ label, value }: { label: string; value: string }) { return <Card className="glass-panel border-white/10"><CardContent className="p-5"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 break-words text-lg font-semibold">{value}</p></CardContent></Card>; }
function StepRow({ step, locale, busy, onApprove }: { step: AutomationStepView; locale: "zh" | "en"; busy: string; onApprove: () => void }) { const Icon = step.status === "COMPLETED" ? CheckCircle2 : step.status === "FAILED" ? XCircle : step.status === "RUNNING" ? Loader2 : step.status === "AWAITING_APPROVAL" ? AlertTriangle : Circle; return <article className={`grid gap-3 rounded-2xl border p-4 sm:grid-cols-[auto_1fr_auto] sm:items-center ${step.status === "AWAITING_APPROVAL" ? "border-amber-300/30 bg-amber-300/[0.06]" : "border-white/10"}`}><Icon className={`h-5 w-5 ${step.status === "RUNNING" ? "animate-spin text-violet-300" : step.status === "COMPLETED" ? "text-emerald-300" : step.status === "FAILED" ? "text-rose-300" : step.status === "AWAITING_APPROVAL" ? "text-amber-300" : "text-muted-foreground"}`} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">Step {step.sequence}: {stepCopy(step, locale)}</strong><Badge variant="outline">{step.riskLevel}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{activityCopy(step, locale)}</p>{step.errorMessage ? <p className="mt-2 text-xs text-rose-200">{step.errorMessage}</p> : null}</div>{step.status === "AWAITING_APPROVAL" ? <div className="sm:text-right"><p className="mb-2 max-w-sm text-xs text-amber-100">{locale === "zh" ? "将发出 1 次真实外部请求，可能产生费用。" : "One real external request will be sent and may incur cost."}</p><Button className="min-h-11" onClick={onApprove} disabled={busy !== ""}>{busy === `approve:${step.id}` ? <Loader2 className="h-4 w-4 animate-spin" /> : <Play className="h-4 w-4" />}{locale === "zh" ? "确认继续" : "Approve and continue"}</Button></div> : step.durationMs !== null ? <span className="text-xs text-muted-foreground">{step.durationMs}ms</span> : null}</article>; }
function MetricComparison({ item, locale }: { item: { key: string; before: { value: number | null; sourceId: string | null; sourceType: string }; after: { value: number | null; sourceId: string | null; sourceType: string } }; locale: "zh" | "en" }) { const labels: Record<string, [string, string]> = { seoHealth: ["SEO 健康度", "SEO Health"], aiVisibility: ["AI 可见性", "AI Visibility"], knowledgeCompleteness: ["知识完整度", "Knowledge Completeness"], citationCount: ["引用数量", "Citation Count"], entityAuthority: ["实体权威度", "Entity Authority"] }; const available = item.before.value !== null && item.after.value !== null; const label = labels[item.key]?.[locale === "zh" ? 0 : 1] ?? item.key; return <div className="min-w-0 rounded-2xl border border-white/10 p-4"><div className="flex items-center justify-between gap-1"><p className="text-xs text-muted-foreground">{label}</p><MetricHelp label={label} content={{ what: locale === "zh" ? "该指标在本次执行前后的真实记录。" : "The real metric recorded before and after this run.", why: locale === "zh" ? "用于验证操作是否产生可测量变化。" : "It verifies whether the run produced a measurable change.", source: item.after.sourceType, improve: locale === "zh" ? "根据对应问题完成优化后重新检测。" : "Complete the related optimization and run another check." }} /></div><p className="mt-3 text-lg font-semibold">{available ? <>{item.before.value} <ArrowRight className="inline h-4 w-4" /> {item.after.value}</> : "Unavailable"}</p><p className="mt-2 truncate text-[10px] text-muted-foreground" title={`${item.before.sourceId ?? "unavailable"} → ${item.after.sourceId ?? "unavailable"}`}>{item.before.sourceId ?? "unavailable"} → {item.after.sourceId ?? "unavailable"}</p></div>; }
