import { realAISearchDatabase, type Row } from "@/features/real-ai-search/database";
import type { AutomationEvidenceSnapshot, AutomationMode, AutomationRunStatus, AutomationRunView, AutomationStepDefinition, AutomationStepStatus, AutomationStepView } from "./types";

const iso = (value: unknown) => value ? new Date(String(value)).toISOString() : null;
function object(value: unknown): Record<string, unknown> { if (value && typeof value === "object" && !Array.isArray(value)) return value as Record<string, unknown>; if (typeof value === "string") { try { const parsed = JSON.parse(value) as unknown; return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed as Record<string, unknown> : {}; } catch { return {}; } } return {}; }
function stepView(row: Row): AutomationStepView { return { id: String(row.id), runId: String(row.runId), projectId: String(row.projectId), sequence: Number(row.sequence), stepKey: String(row.stepKey), stepType: String(row.stepType), riskLevel: String(row.riskLevel) as AutomationStepView["riskLevel"], status: String(row.status) as AutomationStepStatus, title: String(row.title), activityMessage: String(row.activityMessage), inputEvidence: object(row.inputEvidence), outputEvidence: row.outputEvidence ? object(row.outputEvidence) : null, approvalSummary: row.approvalSummary ? object(row.approvalSummary) : null, approvedBy: row.approvedBy ? String(row.approvedBy) : null, approvedAt: iso(row.approvedAt), errorCode: row.errorCode ? String(row.errorCode) : null, errorMessage: row.errorMessage ? String(row.errorMessage) : null, startedAt: iso(row.startedAt), completedAt: iso(row.completedAt), durationMs: row.durationMs === null || row.durationMs === undefined ? null : Number(row.durationMs), createdAt: iso(row.createdAt)!, updatedAt: iso(row.updatedAt)! }; }
function runView(row: Row, steps: AutomationStepView[]): AutomationRunView { return { id: String(row.id), projectId: String(row.projectId), createdBy: String(row.createdBy), mode: String(row.mode) as AutomationMode, status: String(row.status) as AutomationRunStatus, progress: Number(row.progress), currentStepKey: row.currentStepKey ? String(row.currentStepKey) : null, beforeSnapshot: object(row.beforeSnapshot) as AutomationEvidenceSnapshot, afterSnapshot: row.afterSnapshot ? object(row.afterSnapshot) as AutomationEvidenceSnapshot : null, summary: row.summary ? object(row.summary) : null, errorCode: row.errorCode ? String(row.errorCode) : null, errorMessage: row.errorMessage ? String(row.errorMessage) : null, startedAt: iso(row.startedAt), completedAt: iso(row.completedAt), cancelledAt: iso(row.cancelledAt), createdAt: iso(row.createdAt)!, updatedAt: iso(row.updatedAt)!, steps }; }

export const automationRepository = {
  async projectOwned(userId: string, projectId: string) { return Boolean((await realAISearchDatabase().query('SELECT 1 FROM "Project" WHERE "id" = $1 AND "userId" = $2', [projectId, userId]))[0]); },
  async create(userId: string, projectId: string, mode: AutomationMode, before: AutomationEvidenceSnapshot, definitions: AutomationStepDefinition[]) {
    const db = realAISearchDatabase(), runId = crypto.randomUUID(), now = new Date();
    const run = (await db.query('INSERT INTO "AutomationRun" ("id", "projectId", "createdBy", "mode", "status", "progress", "beforeSnapshot", "createdAt", "updatedAt") SELECT $1, p."id", $2, $3::"AutomationMode", \'PREVIEW\'::"AutomationRunStatus", 0, $4::jsonb, $5, $5 FROM "Project" p WHERE p."id" = $6 AND p."userId" = $2 RETURNING "AutomationRun".*', [runId, userId, mode, JSON.stringify(before), now, projectId]))[0];
    if (!run) return null;
    for (let index = 0; index < definitions.length; index += 1) { const item = definitions[index]!; await db.query('INSERT INTO "AutomationStep" ("id", "runId", "projectId", "sequence", "stepKey", "stepType", "riskLevel", "status", "title", "activityMessage", "inputEvidence", "approvalSummary", "createdAt", "updatedAt") VALUES ($1, $2, $3, $4, $5, $6, $7::"AutomationRiskLevel", $8::"AutomationStepStatus", $9, $10, $11::jsonb, $12::jsonb, $13, $13)', [crypto.randomUUID(), runId, projectId, index + 1, item.stepKey, item.stepType, item.riskLevel, item.status ?? "PENDING", item.title, item.activityMessage, JSON.stringify(item.inputEvidence ?? {}), JSON.stringify(item.approvalSummary ?? {}), now]); }
    return this.detail(userId, projectId, runId);
  },
  async detail(userId: string, projectId: string, runId: string) { const db = realAISearchDatabase(); const row = (await db.query('SELECT run.* FROM "AutomationRun" run INNER JOIN "Project" p ON p."id" = run."projectId" WHERE run."id" = $1 AND run."projectId" = $2 AND p."userId" = $3', [runId, projectId, userId]))[0]; if (!row) return null; const steps = (await db.query('SELECT step.* FROM "AutomationStep" step WHERE step."runId" = $1 AND step."projectId" = $2 ORDER BY step."sequence"', [runId, projectId])).map(stepView); return runView(row, steps); },
  async list(userId: string, projectId: string) { const rows = await realAISearchDatabase().query('SELECT run.* FROM "AutomationRun" run INNER JOIN "Project" p ON p."id" = run."projectId" WHERE run."projectId" = $1 AND p."userId" = $2 ORDER BY run."createdAt" DESC LIMIT 30', [projectId, userId]); return Promise.all(rows.map(async row => (await this.detail(userId, projectId, String(row.id)))!)); },
  async setRunStatus(userId: string, projectId: string, runId: string, status: AutomationRunStatus) { const now = new Date(); await realAISearchDatabase().query('UPDATE "AutomationRun" run SET "status" = $4::"AutomationRunStatus", "startedAt" = CASE WHEN $4 = \'RUNNING\' THEN COALESCE(run."startedAt", $5) ELSE run."startedAt" END, "cancelledAt" = CASE WHEN $4 = \'CANCELLED\' THEN $5 ELSE run."cancelledAt" END, "updatedAt" = $5 FROM "Project" p WHERE run."id" = $1 AND run."projectId" = $2 AND p."id" = run."projectId" AND p."userId" = $3', [runId, projectId, userId, status, now]); return this.detail(userId, projectId, runId); },
  async nextOpen(userId: string, projectId: string, runId: string) { const row = (await realAISearchDatabase().query('SELECT step.* FROM "AutomationStep" step INNER JOIN "AutomationRun" run ON run."id" = step."runId" INNER JOIN "Project" p ON p."id" = run."projectId" WHERE step."runId" = $1 AND step."projectId" = $2 AND p."userId" = $3 AND step."status" IN (\'PENDING\', \'AWAITING_APPROVAL\') ORDER BY step."sequence" LIMIT 1', [runId, projectId, userId]))[0]; return row ? stepView(row) : null; },
  async claimStep(userId: string, projectId: string, runId: string, stepId: string) { const now = new Date(); const row = (await realAISearchDatabase().query('UPDATE "AutomationStep" step SET "status" = \'RUNNING\'::"AutomationStepStatus", "startedAt" = $5, "updatedAt" = $5 FROM "AutomationRun" run, "Project" p WHERE step."id" = $1 AND step."runId" = $2 AND step."projectId" = $3 AND step."status" = \'PENDING\' AND run."id" = step."runId" AND run."status" = \'RUNNING\' AND p."id" = step."projectId" AND p."userId" = $4 RETURNING step.*', [stepId, runId, projectId, userId, now]))[0]; if (row) await realAISearchDatabase().query('UPDATE "AutomationRun" SET "currentStepKey" = $2, "updatedAt" = $3 WHERE "id" = $1', [runId, row.stepKey, now]); return row ? stepView(row) : null; },
  async completeStep(userId: string, projectId: string, runId: string, stepId: string, output: Record<string, unknown>) { const now = new Date(); await realAISearchDatabase().query('UPDATE "AutomationStep" step SET "status" = \'COMPLETED\'::"AutomationStepStatus", "outputEvidence" = $5::jsonb, "completedAt" = $6, "durationMs" = GREATEST(0, FLOOR(EXTRACT(EPOCH FROM ($6 - COALESCE(step."startedAt", $6))) * 1000)::int), "updatedAt" = $6 FROM "AutomationRun" run, "Project" p WHERE step."id" = $1 AND step."runId" = $2 AND step."projectId" = $3 AND run."id" = step."runId" AND p."id" = step."projectId" AND p."userId" = $4', [stepId, runId, projectId, userId, JSON.stringify(output), now]); await this.refreshProgress(userId, projectId, runId); return this.detail(userId, projectId, runId); },
  async failStep(userId: string, projectId: string, runId: string, stepId: string, code: string, message: string) { const now = new Date(); await realAISearchDatabase().query('UPDATE "AutomationStep" step SET "status" = \'FAILED\'::"AutomationStepStatus", "errorCode" = $5, "errorMessage" = $6, "completedAt" = $7, "durationMs" = GREATEST(0, FLOOR(EXTRACT(EPOCH FROM ($7 - COALESCE(step."startedAt", $7))) * 1000)::int), "updatedAt" = $7 FROM "Project" p WHERE step."id" = $1 AND step."runId" = $2 AND step."projectId" = $3 AND p."id" = step."projectId" AND p."userId" = $4', [stepId, runId, projectId, userId, code, message, now]); await realAISearchDatabase().query('UPDATE "AutomationRun" run SET "status" = \'FAILED\'::"AutomationRunStatus", "errorCode" = $4, "errorMessage" = $5, "updatedAt" = $6 FROM "Project" p WHERE run."id" = $1 AND run."projectId" = $2 AND p."id" = run."projectId" AND p."userId" = $3', [runId, projectId, userId, code, message, now]); return this.detail(userId, projectId, runId); },
  async approve(userId: string, projectId: string, runId: string, stepId: string) { const now = new Date(); await realAISearchDatabase().query('UPDATE "AutomationStep" step SET "status" = \'PENDING\'::"AutomationStepStatus", "approvedBy" = $4, "approvedAt" = $5, "updatedAt" = $5 FROM "AutomationRun" run, "Project" p WHERE step."id" = $1 AND step."runId" = $2 AND step."projectId" = $3 AND step."status" = \'AWAITING_APPROVAL\' AND run."id" = step."runId" AND p."id" = step."projectId" AND p."userId" = $4', [stepId, runId, projectId, userId, now]); await this.setRunStatus(userId, projectId, runId, "RUNNING"); return this.detail(userId, projectId, runId); },
  async updateBefore(userId: string, projectId: string, runId: string, snapshot: AutomationEvidenceSnapshot) { await realAISearchDatabase().query('UPDATE "AutomationRun" run SET "beforeSnapshot" = $4::jsonb, "updatedAt" = $5 FROM "Project" p WHERE run."id" = $1 AND run."projectId" = $2 AND p."id" = run."projectId" AND p."userId" = $3', [runId, projectId, userId, JSON.stringify(snapshot), new Date()]); },
  async updateAfter(userId: string, projectId: string, runId: string, snapshot: AutomationEvidenceSnapshot) { await realAISearchDatabase().query('UPDATE "AutomationRun" run SET "afterSnapshot" = $4::jsonb, "updatedAt" = $5 FROM "Project" p WHERE run."id" = $1 AND run."projectId" = $2 AND p."id" = run."projectId" AND p."userId" = $3', [runId, projectId, userId, JSON.stringify(snapshot), new Date()]); },
  async refreshProgress(userId: string, projectId: string, runId: string) { const now = new Date(); await realAISearchDatabase().query('WITH counts AS (SELECT COUNT(*)::int AS total, COUNT(*) FILTER (WHERE step."status" IN (\'COMPLETED\', \'SKIPPED\'))::int AS done FROM "AutomationStep" step WHERE step."runId" = $1), owned AS (SELECT run."id" FROM "AutomationRun" run INNER JOIN "Project" p ON p."id" = run."projectId" WHERE run."id" = $1 AND run."projectId" = $2 AND p."userId" = $3) UPDATE "AutomationRun" run SET "progress" = CASE WHEN counts.total = 0 THEN 0 ELSE ROUND(counts.done * 100.0 / counts.total)::int END, "updatedAt" = $4 FROM counts, owned WHERE run."id" = owned."id"', [runId, projectId, userId, now]); },
  async completeRun(userId: string, projectId: string, runId: string, summary: Record<string, unknown>) { const now = new Date(); await realAISearchDatabase().query('UPDATE "AutomationRun" run SET "status" = \'COMPLETED\'::"AutomationRunStatus", "progress" = 100, "summary" = $4::jsonb, "currentStepKey" = NULL, "completedAt" = $5, "updatedAt" = $5 FROM "Project" p WHERE run."id" = $1 AND run."projectId" = $2 AND p."id" = run."projectId" AND p."userId" = $3', [runId, projectId, userId, JSON.stringify(summary), now]); return this.detail(userId, projectId, runId); },
  async cancelPending(userId: string, projectId: string, runId: string) { await realAISearchDatabase().query('UPDATE "AutomationStep" step SET "status" = \'CANCELLED\'::"AutomationStepStatus", "updatedAt" = $4 FROM "Project" p WHERE step."runId" = $1 AND step."projectId" = $2 AND step."status" IN (\'PENDING\', \'AWAITING_APPROVAL\') AND p."id" = step."projectId" AND p."userId" = $3', [runId, projectId, userId, new Date()]); },
};
